///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class SK {
/*
{
  "id": 28041,
  "tipe": 1,
  "nama": "Colley Windya Tyas Buwana",
  "noinduk": "202203123508177",
  "universitas": "University of Chicago",
  "prodi": "Master of Public Policy",
  "negara": "Amerika Serikat",
  "mulaistudi": "2022-09-27",
  "akhirstudi": "2024-06-01",
  "namabaru": null,
  "alasangantinama": null,
  "lampirangantinama": null,
  "mulaistudibaru": null,
  "alasangantimulaistudi": null,
  "lampirangantimulaistudi": null,
  "akhirstudibaru": null,
  "alasangantiakhirstudi": null,
  "lampirangantiakhirstudi": null,
  "tglsubmit": "2023-03-10 20:41:28",
  "status": "Disetujui",
  "rekomendedpic": null,
  "picverif": null,
  "tglverifpic": null,
  "catatanpic": null,
  "pesancpb": null,
  "kasubdivverif": null,
  "tglverifkasubdiv": null,
  "catatankasubdiv": null,
  "kadivverif": null,
  "tglverifkadiv": null,
  "catatankadiv": null,
  "direkturverif": null,
  "tglverifdirektur": "2023-04-14 22:00:55",
  "catatandirektur": "",
  "docsk": "/Dokumen/SK/2023/Signing_SK_1711_20230414_220054019.pdf",
  "nosk": "KEP-469/LPDP/LPDP.3/2022",
  "issigning": 1,
  "logsigning": "",
  "ipsigning": "202.51.110.180",
  "browsersigning": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36",
  "jenispengajuan": null,
  "universitasbaru": null,
  "alasangantiuniversitas": null,
  "prodibaru": null,
  "alasangantiprodi": null,
  "catatankontrak": null,
  "issipendob": 1,
  "signeddate": "2023-04-14 22:00:55",
  "signedid": null,
  "countnosk": null,
  "tglpenerbitansp": "2022-03-09 00:00:00",
  "jenisrevisiid": 1,
  "komponenprogramjenjangid": 37,
  "lastsp": null,
  "iduniversitas": 75,
  "alamatuniversitas": null,
  "isdeleted": null,
  "kode_registrasi": "0000171/SOC/M/19/lpdp2021",
  "nik": "3402121803940004",
  "batch_seleksi": "Tahap 1 2021",
  "tahun_lolos_seleksi": 2021,
  "no_sk_seleksi": "KEP-66/LPDP/2021",
  "tanggal_sk_seleksi": "2021-07-22 00:00:00",
  "kategori_pembayaran": "Full Scholarship",
  "jenis_beasiswa": "Umum",
  "program_beasiswa": "Beasiswa Perguruan Tinggi Utama Dunia",
  "jenis_cofunding": "",
  "jenjang_studi": "Magister",
  "tujuan_beasiswa": "Luar Negeri",
  "nama_lengkap": "Colley Windya Tyas Buwana",
  "tempat_lahir": "Surabaya",
  "tanggal_lahir": "Mar 18 1994 12:00:00:AM",
  "jenis_kelamin": "laki-laki",
  "email": "colley.windya@gmail.com",
  "kabkota": "KAB. BANTUL",
  "provinsi": "DI YOGYAKARTA",
  "jenis_pekerjaan": "Peneliti / Perekayasa (Non-PNS)",
  "instansi_kementerian_lembaga": null,
  "bidang_karir": null,
  "sektor_karir": null,
  "bidang_keilmuan": "Social Policy and Administration",
  "prodi_asal": "Ilmu Hubungan Internasional",
  "universitas_asal": "Universitas Indonesia",
  "prodi_tujuan_pendaftaran": "Master of Public Policy",
  "universitas_tujuan_pendaftaran": "University of Chicago",
  "negara_tujuan_pendaftaran": "Amerika Serikat",
  "status_kontrak": "Belum Kontrak",
  "tahun_kontrak": 2022,
  "no_induk_lpdp": "202203123508177",
  "batch_pk": null,
  "jenjang_studi_kontrak": null,
  "tujuan_beasiswa_kontrak": null,
  "universitas_tujuan_kontrak": null,
  "prodi_tujuan_kontrak": "Master of Public Policy",
  "benua_tujuan_kontrak": null,
  "negara_tujuan_kontrak": null,
  "kota_tujuan_kontrak": null,
  "bidang_keilmuan_kontrak": "Social Policy and Administration",
  "awal_studi": "Sep 27 2022 12:00:00:AM",
  "akhir_studi": "Jun  1 2024 12:00:00:AM",
  "status_akademik": "Belum Kontrak",
  "no_sk_penerima_beasiswa": null,
  "tanggal_penerbitan_sp": "Mar  9 2022 12:00:00:AM",
  "jenis_pengajuan": null,
  "awal_studi_disetujui": "Sep 27 2022 12:00:00:AM",
  "akhir_studi_disetujui": "Jun  1 2024 12:00:00:AM",
  "no_surat_crm": null,
  "updated_date": "2023-06-26 13:43:50",
  "modified_by_id": null,
  "alamat": "Kepanjen, Jaranan, RT 09/RW 40, Banguntapan,",
  "nama_bapak": "Darmaningtyas",
  "nama_ibu": "Supriyati",
  "nama_pasangan": "-",
  "status_menikah": "Belum Menikah",
  "is_sp_dikembalikan": 1,
  "kabkota_saat_ini": "Kota Jakarta Timur",
  "alamat_saat_ini": "Bassura City Apartment, Tower D, Unit D 18BK, Jl. Jend. Basuki Rachmat No.1A, Rt.8/Rw.10, Cipinang Besar Sel., Kecamatan Jatinegara, Jatinegara",
  "komponen_biaya_cofunding": "",
  "is_dibuatkan_akun_simonev": 1,
  "negara_tujuan_kontrak_iso_code": null,
  "provinsi_asal_iso_code": "indonesia-yogyakarta",
  "id_universitas_tujuan_kontrak": 75,
  "id_status_akademik": 4,
  "id_status_kontrak": 38,
  "id_program_beasiswa": 7,
  "id_jenjang_studi": 1,
  "id_tujuan_beasiswa": 2,
  "id_kabkota_asal": 423,
  "no_induk_mahasiswa": null,
  "durasi_studi": 20,
  "frekuensi_dana_hidup": null,
  "bahasa_skor_pendaftaran": "8",
  "bahasa_jenis_tes_pendaftaran": "Inggris (IELTS)",
  "email_saat_ini": null,
  "no_hp_saat_ini": "6281289786117",
  "awal_studi_2": null,
  "akhir_studi_2": null,
  "awal_studi_3": null,
  "akhir_studi_3": null,
  "awal_studi_4": null,
  "akhir_studi_4": null,
  "sumber_info_durasi_studi": "LoA",
  "catatan_kontrak": null,
  "link_foto": "https://beasiswalpdp.kemenkeu.go.id/foto/2021/05/04/124811-Colley Windya Tyas Buwana/831227_colley-windya.jpg",
  "tanggal_sk_penerima_beasiswa": null,
  "nama_lengkap_lama": null,
  "id_universitas_tujuan_kontrak_lama": null,
  "prodi_tujuan_kontrak_lama": null,
  "id_tujuan_beasiswa_lama": null,
  "tanggal_sk_penerima_beasiswa_revisi": null,
  "no_sk_penerima_beasiswa_revisi": null,
  "no_sk_penerima_beasiswa_sebelumnya": null,
  "catatan_seleksi": null,
  "nidn": null,
  "nuptk": null,
  "id_sekolah": null,
  "tanggal_sk_berlaku_sejak": null,
  "id_provinsi_saat_ini": null,
  "id_status_beasiswa": 29,
  "id_status_akademik_universitas": null,
  "id_status_pembiayaan": 35,
  "tanggal_deadline_pencarian_loa": "Jul 22 2023 12:00:00:AM",
  "id_kelas": null,
  "awardee_fakultas": null,
  "awardee_nama_pa": null,
  "awardee_telephone_pa": null,
  "awardee_email_pa": null,
  "awardee_nama_promotor": null,
  "awardee_telephone_promotor": null,
  "awardee_email_promotor": null,
  "awardee_tanggal_masuk": null,
  "awardee_batas_studi": null,
  "awardee_tanggal_lulus": null,
  "awardee_tanggal_yudisium": null,
  "awardee_nomor_ijazah": null,
  "perkembangan_ipk": null,
  "awardee_jurusan_universitas": null,
  "pns_unit_eselon_1": null,
  "pns_unit_eselon_2": null,
  "id_fakultas": null,
  "id_program_studi": null,
  "hak_spp": 4,
  "ishaveloafromseleksi": 1
} 
*/

  int? id;
  int? tipe;
  String? nama;
  String? noinduk;
  String? universitas;
  String? prodi;
  String? negara;
  String? mulaistudi;
  String? akhirstudi;
  String? namabaru;
  String? alasangantinama;
  String? lampirangantinama;
  String? mulaistudibaru;
  String? alasangantimulaistudi;
  String? lampirangantimulaistudi;
  String? akhirstudibaru;
  String? alasangantiakhirstudi;
  String? lampirangantiakhirstudi;
  String? tglsubmit;
  String? status;
  String? rekomendedpic;
  String? picverif;
  String? tglverifpic;
  String? catatanpic;
  String? pesancpb;
  String? kasubdivverif;
  String? tglverifkasubdiv;
  String? catatankasubdiv;
  String? kadivverif;
  String? tglverifkadiv;
  String? catatankadiv;
  String? direkturverif;
  String? tglverifdirektur;
  String? catatandirektur;
  String? docsk;
  String? nosk;
  int? issigning;
  String? logsigning;
  String? ipsigning;
  String? browsersigning;
  String? jenispengajuan;
  String? universitasbaru;
  String? alasangantiuniversitas;
  String? prodibaru;
  String? alasangantiprodi;
  String? catatankontrak;
  int? issipendob;
  String? signeddate;
  String? signedid;
  String? countnosk;
  String? tglpenerbitansp;
  int? jenisrevisiid;
  int? komponenprogramjenjangid;
  String? lastsp;
  int? iduniversitas;
  String? alamatuniversitas;
  String? isdeleted;
  String? kodeRegistrasi;
  String? nik;
  String? batchSeleksi;
  int? tahunLolosSeleksi;
  String? noSkSeleksi;
  String? tanggalSkSeleksi;
  String? kategoriPembayaran;
  String? jenisBeasiswa;
  String? programBeasiswa;
  String? jenisCofunding;
  String? jenjangStudi;
  String? tujuanBeasiswa;
  String? namaLengkap;
  String? tempatLahir;
  String? tanggalLahir;
  String? jenisKelamin;
  String? email;
  String? kabkota;
  String? provinsi;
  String? jenisPekerjaan;
  String? instansiKementerianLembaga;
  String? bidangKarir;
  String? sektorKarir;
  String? bidangKeilmuan;
  String? prodiAsal;
  String? universitasAsal;
  String? prodiTujuanPendaftaran;
  String? universitasTujuanPendaftaran;
  String? negaraTujuanPendaftaran;
  String? statusKontrak;
  int? tahunKontrak;
  String? noIndukLpdp;
  String? batchPk;
  String? jenjangStudiKontrak;
  String? tujuanBeasiswaKontrak;
  String? universitasTujuanKontrak;
  String? prodiTujuanKontrak;
  String? benuaTujuanKontrak;
  String? negaraTujuanKontrak;
  String? kotaTujuanKontrak;
  String? bidangKeilmuanKontrak;
  String? awalStudi;
  String? akhirStudi;
  String? statusAkademik;
  String? noSkPenerimaBeasiswa;
  String? tanggalPenerbitanSp;
  String? jenisPengajuan;
  String? awalStudiDisetujui;
  String? akhirStudiDisetujui;
  String? noSuratCrm;
  String? updatedDate;
  String? modifiedById;
  String? alamat;
  String? namaBapak;
  String? namaIbu;
  String? namaPasangan;
  String? statusMenikah;
  int? isSpDikembalikan;
  String? kabkotaSaatIni;
  String? alamatSaatIni;
  String? komponenBiayaCofunding;
  int? isDibuatkanAkunSimonev;
  String? negaraTujuanKontrakIsoCode;
  String? provinsiAsalIsoCode;
  int? idUniversitasTujuanKontrak;
  int? idStatusAkademik;
  int? idStatusKontrak;
  int? idProgramBeasiswa;
  int? idJenjangStudi;
  int? idTujuanBeasiswa;
  int? idKabkotaAsal;
  String? noIndukMahasiswa;
  int? durasiStudi;
  String? frekuensiDanaHidup;
  String? bahasaSkorPendaftaran;
  String? bahasaJenisTesPendaftaran;
  String? emailSaatIni;
  String? noHpSaatIni;
  String? awalStudi_2;
  String? akhirStudi_2;
  String? awalStudi_3;
  String? akhirStudi_3;
  String? awalStudi_4;
  String? akhirStudi_4;
  String? sumberInfoDurasiStudi;
  String? catatanKontrak;
  String? linkFoto;
  String? tanggalSkPenerimaBeasiswa;
  String? namaLengkapLama;
  String? idUniversitasTujuanKontrakLama;
  String? prodiTujuanKontrakLama;
  String? idTujuanBeasiswaLama;
  String? tanggalSkPenerimaBeasiswaRevisi;
  String? noSkPenerimaBeasiswaRevisi;
  String? noSkPenerimaBeasiswaSebelumnya;
  String? catatanSeleksi;
  String? nidn;
  String? nuptk;
  String? idSekolah;
  String? tanggalSkBerlakuSejak;
  String? idProvinsiSaatIni;
  int? idStatusBeasiswa;
  String? idStatusAkademikUniversitas;
  int? idStatusPembiayaan;
  String? tanggalDeadlinePencarianLoa;
  String? idKelas;
  String? awardeeFakultas;
  String? awardeeNamaPa;
  String? awardeeTelephonePa;
  String? awardeeEmailPa;
  String? awardeeNamaPromotor;
  String? awardeeTelephonePromotor;
  String? awardeeEmailPromotor;
  String? awardeeTanggalMasuk;
  String? awardeeBatasStudi;
  String? awardeeTanggalLulus;
  String? awardeeTanggalYudisium;
  String? awardeeNomorIjazah;
  String? perkembanganIpk;
  String? awardeeJurusanUniversitas;
  String? pnsUnitEselon_1;
  String? pnsUnitEselon_2;
  String? idFakultas;
  String? idProgramStudi;
  int? hakSpp;
  int? ishaveloafromseleksi;

  SK({
    this.id,
    this.tipe,
    this.nama,
    this.noinduk,
    this.universitas,
    this.prodi,
    this.negara,
    this.mulaistudi,
    this.akhirstudi,
    this.namabaru,
    this.alasangantinama,
    this.lampirangantinama,
    this.mulaistudibaru,
    this.alasangantimulaistudi,
    this.lampirangantimulaistudi,
    this.akhirstudibaru,
    this.alasangantiakhirstudi,
    this.lampirangantiakhirstudi,
    this.tglsubmit,
    this.status,
    this.rekomendedpic,
    this.picverif,
    this.tglverifpic,
    this.catatanpic,
    this.pesancpb,
    this.kasubdivverif,
    this.tglverifkasubdiv,
    this.catatankasubdiv,
    this.kadivverif,
    this.tglverifkadiv,
    this.catatankadiv,
    this.direkturverif,
    this.tglverifdirektur,
    this.catatandirektur,
    this.docsk,
    this.nosk,
    this.issigning,
    this.logsigning,
    this.ipsigning,
    this.browsersigning,
    this.jenispengajuan,
    this.universitasbaru,
    this.alasangantiuniversitas,
    this.prodibaru,
    this.alasangantiprodi,
    this.catatankontrak,
    this.issipendob,
    this.signeddate,
    this.signedid,
    this.countnosk,
    this.tglpenerbitansp,
    this.jenisrevisiid,
    this.komponenprogramjenjangid,
    this.lastsp,
    this.iduniversitas,
    this.alamatuniversitas,
    this.isdeleted,
    this.kodeRegistrasi,
    this.nik,
    this.batchSeleksi,
    this.tahunLolosSeleksi,
    this.noSkSeleksi,
    this.tanggalSkSeleksi,
    this.kategoriPembayaran,
    this.jenisBeasiswa,
    this.programBeasiswa,
    this.jenisCofunding,
    this.jenjangStudi,
    this.tujuanBeasiswa,
    this.namaLengkap,
    this.tempatLahir,
    this.tanggalLahir,
    this.jenisKelamin,
    this.email,
    this.kabkota,
    this.provinsi,
    this.jenisPekerjaan,
    this.instansiKementerianLembaga,
    this.bidangKarir,
    this.sektorKarir,
    this.bidangKeilmuan,
    this.prodiAsal,
    this.universitasAsal,
    this.prodiTujuanPendaftaran,
    this.universitasTujuanPendaftaran,
    this.negaraTujuanPendaftaran,
    this.statusKontrak,
    this.tahunKontrak,
    this.noIndukLpdp,
    this.batchPk,
    this.jenjangStudiKontrak,
    this.tujuanBeasiswaKontrak,
    this.universitasTujuanKontrak,
    this.prodiTujuanKontrak,
    this.benuaTujuanKontrak,
    this.negaraTujuanKontrak,
    this.kotaTujuanKontrak,
    this.bidangKeilmuanKontrak,
    this.awalStudi,
    this.akhirStudi,
    this.statusAkademik,
    this.noSkPenerimaBeasiswa,
    this.tanggalPenerbitanSp,
    this.jenisPengajuan,
    this.awalStudiDisetujui,
    this.akhirStudiDisetujui,
    this.noSuratCrm,
    this.updatedDate,
    this.modifiedById,
    this.alamat,
    this.namaBapak,
    this.namaIbu,
    this.namaPasangan,
    this.statusMenikah,
    this.isSpDikembalikan,
    this.kabkotaSaatIni,
    this.alamatSaatIni,
    this.komponenBiayaCofunding,
    this.isDibuatkanAkunSimonev,
    this.negaraTujuanKontrakIsoCode,
    this.provinsiAsalIsoCode,
    this.idUniversitasTujuanKontrak,
    this.idStatusAkademik,
    this.idStatusKontrak,
    this.idProgramBeasiswa,
    this.idJenjangStudi,
    this.idTujuanBeasiswa,
    this.idKabkotaAsal,
    this.noIndukMahasiswa,
    this.durasiStudi,
    this.frekuensiDanaHidup,
    this.bahasaSkorPendaftaran,
    this.bahasaJenisTesPendaftaran,
    this.emailSaatIni,
    this.noHpSaatIni,
    this.awalStudi_2,
    this.akhirStudi_2,
    this.awalStudi_3,
    this.akhirStudi_3,
    this.awalStudi_4,
    this.akhirStudi_4,
    this.sumberInfoDurasiStudi,
    this.catatanKontrak,
    this.linkFoto,
    this.tanggalSkPenerimaBeasiswa,
    this.namaLengkapLama,
    this.idUniversitasTujuanKontrakLama,
    this.prodiTujuanKontrakLama,
    this.idTujuanBeasiswaLama,
    this.tanggalSkPenerimaBeasiswaRevisi,
    this.noSkPenerimaBeasiswaRevisi,
    this.noSkPenerimaBeasiswaSebelumnya,
    this.catatanSeleksi,
    this.nidn,
    this.nuptk,
    this.idSekolah,
    this.tanggalSkBerlakuSejak,
    this.idProvinsiSaatIni,
    this.idStatusBeasiswa,
    this.idStatusAkademikUniversitas,
    this.idStatusPembiayaan,
    this.tanggalDeadlinePencarianLoa,
    this.idKelas,
    this.awardeeFakultas,
    this.awardeeNamaPa,
    this.awardeeTelephonePa,
    this.awardeeEmailPa,
    this.awardeeNamaPromotor,
    this.awardeeTelephonePromotor,
    this.awardeeEmailPromotor,
    this.awardeeTanggalMasuk,
    this.awardeeBatasStudi,
    this.awardeeTanggalLulus,
    this.awardeeTanggalYudisium,
    this.awardeeNomorIjazah,
    this.perkembanganIpk,
    this.awardeeJurusanUniversitas,
    this.pnsUnitEselon_1,
    this.pnsUnitEselon_2,
    this.idFakultas,
    this.idProgramStudi,
    this.hakSpp,
    this.ishaveloafromseleksi,
  });
  SK.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    tipe = json['tipe']?.toInt();
    nama = json['nama']?.toString();
    noinduk = json['noinduk']?.toString();
    universitas = json['universitas']?.toString();
    prodi = json['prodi']?.toString();
    negara = json['negara']?.toString();
    mulaistudi = json['mulaistudi']?.toString();
    akhirstudi = json['akhirstudi']?.toString();
    namabaru = json['namabaru']?.toString();
    alasangantinama = json['alasangantinama']?.toString();
    lampirangantinama = json['lampirangantinama']?.toString();
    mulaistudibaru = json['mulaistudibaru']?.toString();
    alasangantimulaistudi = json['alasangantimulaistudi']?.toString();
    lampirangantimulaistudi = json['lampirangantimulaistudi']?.toString();
    akhirstudibaru = json['akhirstudibaru']?.toString();
    alasangantiakhirstudi = json['alasangantiakhirstudi']?.toString();
    lampirangantiakhirstudi = json['lampirangantiakhirstudi']?.toString();
    tglsubmit = json['tglsubmit']?.toString();
    status = json['status']?.toString();
    rekomendedpic = json['rekomendedpic']?.toString();
    picverif = json['picverif']?.toString();
    tglverifpic = json['tglverifpic']?.toString();
    catatanpic = json['catatanpic']?.toString();
    pesancpb = json['pesancpb']?.toString();
    kasubdivverif = json['kasubdivverif']?.toString();
    tglverifkasubdiv = json['tglverifkasubdiv']?.toString();
    catatankasubdiv = json['catatankasubdiv']?.toString();
    kadivverif = json['kadivverif']?.toString();
    tglverifkadiv = json['tglverifkadiv']?.toString();
    catatankadiv = json['catatankadiv']?.toString();
    direkturverif = json['direkturverif']?.toString();
    tglverifdirektur = json['tglverifdirektur']?.toString();
    catatandirektur = json['catatandirektur']?.toString();
    docsk = json['docsk']?.toString();
    nosk = json['nosk']?.toString();
    issigning = json['issigning']?.toInt();
    logsigning = json['logsigning']?.toString();
    ipsigning = json['ipsigning']?.toString();
    browsersigning = json['browsersigning']?.toString();
    jenispengajuan = json['jenispengajuan']?.toString();
    universitasbaru = json['universitasbaru']?.toString();
    alasangantiuniversitas = json['alasangantiuniversitas']?.toString();
    prodibaru = json['prodibaru']?.toString();
    alasangantiprodi = json['alasangantiprodi']?.toString();
    catatankontrak = json['catatankontrak']?.toString();
    issipendob = json['issipendob']?.toInt();
    signeddate = json['signeddate']?.toString();
    signedid = json['signedid']?.toString();
    countnosk = json['countnosk']?.toString();
    tglpenerbitansp = json['tglpenerbitansp']?.toString();
    jenisrevisiid = json['jenisrevisiid']?.toInt();
    komponenprogramjenjangid = json['komponenprogramjenjangid']?.toInt();
    lastsp = json['lastsp']?.toString();
    iduniversitas = json['iduniversitas']?.toInt();
    alamatuniversitas = json['alamatuniversitas']?.toString();
    isdeleted = json['isdeleted']?.toString();
    kodeRegistrasi = json['kode_registrasi']?.toString();
    nik = json['nik']?.toString();
    batchSeleksi = json['batch_seleksi']?.toString();
    tahunLolosSeleksi = json['tahun_lolos_seleksi']?.toInt();
    noSkSeleksi = json['no_sk_seleksi']?.toString();
    tanggalSkSeleksi = json['tanggal_sk_seleksi']?.toString();
    kategoriPembayaran = json['kategori_pembayaran']?.toString();
    jenisBeasiswa = json['jenis_beasiswa']?.toString();
    programBeasiswa = json['program_beasiswa']?.toString();
    jenisCofunding = json['jenis_cofunding']?.toString();
    jenjangStudi = json['jenjang_studi']?.toString();
    tujuanBeasiswa = json['tujuan_beasiswa']?.toString();
    namaLengkap = json['nama_lengkap']?.toString();
    tempatLahir = json['tempat_lahir']?.toString();
    tanggalLahir = json['tanggal_lahir']?.toString();
    jenisKelamin = json['jenis_kelamin']?.toString();
    email = json['email']?.toString();
    kabkota = json['kabkota']?.toString();
    provinsi = json['provinsi']?.toString();
    jenisPekerjaan = json['jenis_pekerjaan']?.toString();
    instansiKementerianLembaga = json['instansi_kementerian_lembaga']?.toString();
    bidangKarir = json['bidang_karir']?.toString();
    sektorKarir = json['sektor_karir']?.toString();
    bidangKeilmuan = json['bidang_keilmuan']?.toString();
    prodiAsal = json['prodi_asal']?.toString();
    universitasAsal = json['universitas_asal']?.toString();
    prodiTujuanPendaftaran = json['prodi_tujuan_pendaftaran']?.toString();
    universitasTujuanPendaftaran = json['universitas_tujuan_pendaftaran']?.toString();
    negaraTujuanPendaftaran = json['negara_tujuan_pendaftaran']?.toString();
    statusKontrak = json['status_kontrak']?.toString();
    tahunKontrak = json['tahun_kontrak']?.toInt();
    noIndukLpdp = json['no_induk_lpdp']?.toString();
    batchPk = json['batch_pk']?.toString();
    jenjangStudiKontrak = json['jenjang_studi_kontrak']?.toString();
    tujuanBeasiswaKontrak = json['tujuan_beasiswa_kontrak']?.toString();
    universitasTujuanKontrak = json['universitas_tujuan_kontrak']?.toString();
    prodiTujuanKontrak = json['prodi_tujuan_kontrak']?.toString();
    benuaTujuanKontrak = json['benua_tujuan_kontrak']?.toString();
    negaraTujuanKontrak = json['negara_tujuan_kontrak']?.toString();
    kotaTujuanKontrak = json['kota_tujuan_kontrak']?.toString();
    bidangKeilmuanKontrak = json['bidang_keilmuan_kontrak']?.toString();
    awalStudi = json['awal_studi']?.toString();
    akhirStudi = json['akhir_studi']?.toString();
    statusAkademik = json['status_akademik']?.toString();
    noSkPenerimaBeasiswa = json['no_sk_penerima_beasiswa']?.toString();
    tanggalPenerbitanSp = json['tanggal_penerbitan_sp']?.toString();
    jenisPengajuan = json['jenis_pengajuan']?.toString();
    awalStudiDisetujui = json['awal_studi_disetujui']?.toString();
    akhirStudiDisetujui = json['akhir_studi_disetujui']?.toString();
    noSuratCrm = json['no_surat_crm']?.toString();
    updatedDate = json['updated_date']?.toString();
    modifiedById = json['modified_by_id']?.toString();
    alamat = json['alamat']?.toString();
    namaBapak = json['nama_bapak']?.toString();
    namaIbu = json['nama_ibu']?.toString();
    namaPasangan = json['nama_pasangan']?.toString();
    statusMenikah = json['status_menikah']?.toString();
    isSpDikembalikan = json['is_sp_dikembalikan']?.toInt();
    kabkotaSaatIni = json['kabkota_saat_ini']?.toString();
    alamatSaatIni = json['alamat_saat_ini']?.toString();
    komponenBiayaCofunding = json['komponen_biaya_cofunding']?.toString();
    isDibuatkanAkunSimonev = json['is_dibuatkan_akun_simonev']?.toInt();
    negaraTujuanKontrakIsoCode = json['negara_tujuan_kontrak_iso_code']?.toString();
    provinsiAsalIsoCode = json['provinsi_asal_iso_code']?.toString();
    idUniversitasTujuanKontrak = json['id_universitas_tujuan_kontrak']?.toInt();
    idStatusAkademik = json['id_status_akademik']?.toInt();
    idStatusKontrak = json['id_status_kontrak']?.toInt();
    idProgramBeasiswa = json['id_program_beasiswa']?.toInt();
    idJenjangStudi = json['id_jenjang_studi']?.toInt();
    idTujuanBeasiswa = json['id_tujuan_beasiswa']?.toInt();
    idKabkotaAsal = json['id_kabkota_asal']?.toInt();
    noIndukMahasiswa = json['no_induk_mahasiswa']?.toString();
    durasiStudi = json['durasi_studi']?.toInt();
    frekuensiDanaHidup = json['frekuensi_dana_hidup']?.toString();
    bahasaSkorPendaftaran = json['bahasa_skor_pendaftaran']?.toString();
    bahasaJenisTesPendaftaran = json['bahasa_jenis_tes_pendaftaran']?.toString();
    emailSaatIni = json['email_saat_ini']?.toString();
    noHpSaatIni = json['no_hp_saat_ini']?.toString();
    awalStudi_2 = json['awal_studi_2']?.toString();
    akhirStudi_2 = json['akhir_studi_2']?.toString();
    awalStudi_3 = json['awal_studi_3']?.toString();
    akhirStudi_3 = json['akhir_studi_3']?.toString();
    awalStudi_4 = json['awal_studi_4']?.toString();
    akhirStudi_4 = json['akhir_studi_4']?.toString();
    sumberInfoDurasiStudi = json['sumber_info_durasi_studi']?.toString();
    catatanKontrak = json['catatan_kontrak']?.toString();
    linkFoto = json['link_foto']?.toString();
    tanggalSkPenerimaBeasiswa = json['tanggal_sk_penerima_beasiswa']?.toString();
    namaLengkapLama = json['nama_lengkap_lama']?.toString();
    idUniversitasTujuanKontrakLama = json['id_universitas_tujuan_kontrak_lama']?.toString();
    prodiTujuanKontrakLama = json['prodi_tujuan_kontrak_lama']?.toString();
    idTujuanBeasiswaLama = json['id_tujuan_beasiswa_lama']?.toString();
    tanggalSkPenerimaBeasiswaRevisi = json['tanggal_sk_penerima_beasiswa_revisi']?.toString();
    noSkPenerimaBeasiswaRevisi = json['no_sk_penerima_beasiswa_revisi']?.toString();
    noSkPenerimaBeasiswaSebelumnya = json['no_sk_penerima_beasiswa_sebelumnya']?.toString();
    catatanSeleksi = json['catatan_seleksi']?.toString();
    nidn = json['nidn']?.toString();
    nuptk = json['nuptk']?.toString();
    idSekolah = json['id_sekolah']?.toString();
    tanggalSkBerlakuSejak = json['tanggal_sk_berlaku_sejak']?.toString();
    idProvinsiSaatIni = json['id_provinsi_saat_ini']?.toString();
    idStatusBeasiswa = json['id_status_beasiswa']?.toInt();
    idStatusAkademikUniversitas = json['id_status_akademik_universitas']?.toString();
    idStatusPembiayaan = json['id_status_pembiayaan']?.toInt();
    tanggalDeadlinePencarianLoa = json['tanggal_deadline_pencarian_loa']?.toString();
    idKelas = json['id_kelas']?.toString();
    awardeeFakultas = json['awardee_fakultas']?.toString();
    awardeeNamaPa = json['awardee_nama_pa']?.toString();
    awardeeTelephonePa = json['awardee_telephone_pa']?.toString();
    awardeeEmailPa = json['awardee_email_pa']?.toString();
    awardeeNamaPromotor = json['awardee_nama_promotor']?.toString();
    awardeeTelephonePromotor = json['awardee_telephone_promotor']?.toString();
    awardeeEmailPromotor = json['awardee_email_promotor']?.toString();
    awardeeTanggalMasuk = json['awardee_tanggal_masuk']?.toString();
    awardeeBatasStudi = json['awardee_batas_studi']?.toString();
    awardeeTanggalLulus = json['awardee_tanggal_lulus']?.toString();
    awardeeTanggalYudisium = json['awardee_tanggal_yudisium']?.toString();
    awardeeNomorIjazah = json['awardee_nomor_ijazah']?.toString();
    perkembanganIpk = json['perkembangan_ipk']?.toString();
    awardeeJurusanUniversitas = json['awardee_jurusan_universitas']?.toString();
    pnsUnitEselon_1 = json['pns_unit_eselon_1']?.toString();
    pnsUnitEselon_2 = json['pns_unit_eselon_2']?.toString();
    idFakultas = json['id_fakultas']?.toString();
    idProgramStudi = json['id_program_studi']?.toString();
    hakSpp = json['hak_spp']?.toInt();
    ishaveloafromseleksi = json['ishaveloafromseleksi']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['tipe'] = tipe;
    data['nama'] = nama;
    data['noinduk'] = noinduk;
    data['universitas'] = universitas;
    data['prodi'] = prodi;
    data['negara'] = negara;
    data['mulaistudi'] = mulaistudi;
    data['akhirstudi'] = akhirstudi;
    data['namabaru'] = namabaru;
    data['alasangantinama'] = alasangantinama;
    data['lampirangantinama'] = lampirangantinama;
    data['mulaistudibaru'] = mulaistudibaru;
    data['alasangantimulaistudi'] = alasangantimulaistudi;
    data['lampirangantimulaistudi'] = lampirangantimulaistudi;
    data['akhirstudibaru'] = akhirstudibaru;
    data['alasangantiakhirstudi'] = alasangantiakhirstudi;
    data['lampirangantiakhirstudi'] = lampirangantiakhirstudi;
    data['tglsubmit'] = tglsubmit;
    data['status'] = status;
    data['rekomendedpic'] = rekomendedpic;
    data['picverif'] = picverif;
    data['tglverifpic'] = tglverifpic;
    data['catatanpic'] = catatanpic;
    data['pesancpb'] = pesancpb;
    data['kasubdivverif'] = kasubdivverif;
    data['tglverifkasubdiv'] = tglverifkasubdiv;
    data['catatankasubdiv'] = catatankasubdiv;
    data['kadivverif'] = kadivverif;
    data['tglverifkadiv'] = tglverifkadiv;
    data['catatankadiv'] = catatankadiv;
    data['direkturverif'] = direkturverif;
    data['tglverifdirektur'] = tglverifdirektur;
    data['catatandirektur'] = catatandirektur;
    data['docsk'] = docsk;
    data['nosk'] = nosk;
    data['issigning'] = issigning;
    data['logsigning'] = logsigning;
    data['ipsigning'] = ipsigning;
    data['browsersigning'] = browsersigning;
    data['jenispengajuan'] = jenispengajuan;
    data['universitasbaru'] = universitasbaru;
    data['alasangantiuniversitas'] = alasangantiuniversitas;
    data['prodibaru'] = prodibaru;
    data['alasangantiprodi'] = alasangantiprodi;
    data['catatankontrak'] = catatankontrak;
    data['issipendob'] = issipendob;
    data['signeddate'] = signeddate;
    data['signedid'] = signedid;
    data['countnosk'] = countnosk;
    data['tglpenerbitansp'] = tglpenerbitansp;
    data['jenisrevisiid'] = jenisrevisiid;
    data['komponenprogramjenjangid'] = komponenprogramjenjangid;
    data['lastsp'] = lastsp;
    data['iduniversitas'] = iduniversitas;
    data['alamatuniversitas'] = alamatuniversitas;
    data['isdeleted'] = isdeleted;
    data['kode_registrasi'] = kodeRegistrasi;
    data['nik'] = nik;
    data['batch_seleksi'] = batchSeleksi;
    data['tahun_lolos_seleksi'] = tahunLolosSeleksi;
    data['no_sk_seleksi'] = noSkSeleksi;
    data['tanggal_sk_seleksi'] = tanggalSkSeleksi;
    data['kategori_pembayaran'] = kategoriPembayaran;
    data['jenis_beasiswa'] = jenisBeasiswa;
    data['program_beasiswa'] = programBeasiswa;
    data['jenis_cofunding'] = jenisCofunding;
    data['jenjang_studi'] = jenjangStudi;
    data['tujuan_beasiswa'] = tujuanBeasiswa;
    data['nama_lengkap'] = namaLengkap;
    data['tempat_lahir'] = tempatLahir;
    data['tanggal_lahir'] = tanggalLahir;
    data['jenis_kelamin'] = jenisKelamin;
    data['email'] = email;
    data['kabkota'] = kabkota;
    data['provinsi'] = provinsi;
    data['jenis_pekerjaan'] = jenisPekerjaan;
    data['instansi_kementerian_lembaga'] = instansiKementerianLembaga;
    data['bidang_karir'] = bidangKarir;
    data['sektor_karir'] = sektorKarir;
    data['bidang_keilmuan'] = bidangKeilmuan;
    data['prodi_asal'] = prodiAsal;
    data['universitas_asal'] = universitasAsal;
    data['prodi_tujuan_pendaftaran'] = prodiTujuanPendaftaran;
    data['universitas_tujuan_pendaftaran'] = universitasTujuanPendaftaran;
    data['negara_tujuan_pendaftaran'] = negaraTujuanPendaftaran;
    data['status_kontrak'] = statusKontrak;
    data['tahun_kontrak'] = tahunKontrak;
    data['no_induk_lpdp'] = noIndukLpdp;
    data['batch_pk'] = batchPk;
    data['jenjang_studi_kontrak'] = jenjangStudiKontrak;
    data['tujuan_beasiswa_kontrak'] = tujuanBeasiswaKontrak;
    data['universitas_tujuan_kontrak'] = universitasTujuanKontrak;
    data['prodi_tujuan_kontrak'] = prodiTujuanKontrak;
    data['benua_tujuan_kontrak'] = benuaTujuanKontrak;
    data['negara_tujuan_kontrak'] = negaraTujuanKontrak;
    data['kota_tujuan_kontrak'] = kotaTujuanKontrak;
    data['bidang_keilmuan_kontrak'] = bidangKeilmuanKontrak;
    data['awal_studi'] = awalStudi;
    data['akhir_studi'] = akhirStudi;
    data['status_akademik'] = statusAkademik;
    data['no_sk_penerima_beasiswa'] = noSkPenerimaBeasiswa;
    data['tanggal_penerbitan_sp'] = tanggalPenerbitanSp;
    data['jenis_pengajuan'] = jenisPengajuan;
    data['awal_studi_disetujui'] = awalStudiDisetujui;
    data['akhir_studi_disetujui'] = akhirStudiDisetujui;
    data['no_surat_crm'] = noSuratCrm;
    data['updated_date'] = updatedDate;
    data['modified_by_id'] = modifiedById;
    data['alamat'] = alamat;
    data['nama_bapak'] = namaBapak;
    data['nama_ibu'] = namaIbu;
    data['nama_pasangan'] = namaPasangan;
    data['status_menikah'] = statusMenikah;
    data['is_sp_dikembalikan'] = isSpDikembalikan;
    data['kabkota_saat_ini'] = kabkotaSaatIni;
    data['alamat_saat_ini'] = alamatSaatIni;
    data['komponen_biaya_cofunding'] = komponenBiayaCofunding;
    data['is_dibuatkan_akun_simonev'] = isDibuatkanAkunSimonev;
    data['negara_tujuan_kontrak_iso_code'] = negaraTujuanKontrakIsoCode;
    data['provinsi_asal_iso_code'] = provinsiAsalIsoCode;
    data['id_universitas_tujuan_kontrak'] = idUniversitasTujuanKontrak;
    data['id_status_akademik'] = idStatusAkademik;
    data['id_status_kontrak'] = idStatusKontrak;
    data['id_program_beasiswa'] = idProgramBeasiswa;
    data['id_jenjang_studi'] = idJenjangStudi;
    data['id_tujuan_beasiswa'] = idTujuanBeasiswa;
    data['id_kabkota_asal'] = idKabkotaAsal;
    data['no_induk_mahasiswa'] = noIndukMahasiswa;
    data['durasi_studi'] = durasiStudi;
    data['frekuensi_dana_hidup'] = frekuensiDanaHidup;
    data['bahasa_skor_pendaftaran'] = bahasaSkorPendaftaran;
    data['bahasa_jenis_tes_pendaftaran'] = bahasaJenisTesPendaftaran;
    data['email_saat_ini'] = emailSaatIni;
    data['no_hp_saat_ini'] = noHpSaatIni;
    data['awal_studi_2'] = awalStudi_2;
    data['akhir_studi_2'] = akhirStudi_2;
    data['awal_studi_3'] = awalStudi_3;
    data['akhir_studi_3'] = akhirStudi_3;
    data['awal_studi_4'] = awalStudi_4;
    data['akhir_studi_4'] = akhirStudi_4;
    data['sumber_info_durasi_studi'] = sumberInfoDurasiStudi;
    data['catatan_kontrak'] = catatanKontrak;
    data['link_foto'] = linkFoto;
    data['tanggal_sk_penerima_beasiswa'] = tanggalSkPenerimaBeasiswa;
    data['nama_lengkap_lama'] = namaLengkapLama;
    data['id_universitas_tujuan_kontrak_lama'] = idUniversitasTujuanKontrakLama;
    data['prodi_tujuan_kontrak_lama'] = prodiTujuanKontrakLama;
    data['id_tujuan_beasiswa_lama'] = idTujuanBeasiswaLama;
    data['tanggal_sk_penerima_beasiswa_revisi'] = tanggalSkPenerimaBeasiswaRevisi;
    data['no_sk_penerima_beasiswa_revisi'] = noSkPenerimaBeasiswaRevisi;
    data['no_sk_penerima_beasiswa_sebelumnya'] = noSkPenerimaBeasiswaSebelumnya;
    data['catatan_seleksi'] = catatanSeleksi;
    data['nidn'] = nidn;
    data['nuptk'] = nuptk;
    data['id_sekolah'] = idSekolah;
    data['tanggal_sk_berlaku_sejak'] = tanggalSkBerlakuSejak;
    data['id_provinsi_saat_ini'] = idProvinsiSaatIni;
    data['id_status_beasiswa'] = idStatusBeasiswa;
    data['id_status_akademik_universitas'] = idStatusAkademikUniversitas;
    data['id_status_pembiayaan'] = idStatusPembiayaan;
    data['tanggal_deadline_pencarian_loa'] = tanggalDeadlinePencarianLoa;
    data['id_kelas'] = idKelas;
    data['awardee_fakultas'] = awardeeFakultas;
    data['awardee_nama_pa'] = awardeeNamaPa;
    data['awardee_telephone_pa'] = awardeeTelephonePa;
    data['awardee_email_pa'] = awardeeEmailPa;
    data['awardee_nama_promotor'] = awardeeNamaPromotor;
    data['awardee_telephone_promotor'] = awardeeTelephonePromotor;
    data['awardee_email_promotor'] = awardeeEmailPromotor;
    data['awardee_tanggal_masuk'] = awardeeTanggalMasuk;
    data['awardee_batas_studi'] = awardeeBatasStudi;
    data['awardee_tanggal_lulus'] = awardeeTanggalLulus;
    data['awardee_tanggal_yudisium'] = awardeeTanggalYudisium;
    data['awardee_nomor_ijazah'] = awardeeNomorIjazah;
    data['perkembangan_ipk'] = perkembanganIpk;
    data['awardee_jurusan_universitas'] = awardeeJurusanUniversitas;
    data['pns_unit_eselon_1'] = pnsUnitEselon_1;
    data['pns_unit_eselon_2'] = pnsUnitEselon_2;
    data['id_fakultas'] = idFakultas;
    data['id_program_studi'] = idProgramStudi;
    data['hak_spp'] = hakSpp;
    data['ishaveloafromseleksi'] = ishaveloafromseleksi;
    return data;
  }
}
