///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class UserProfileInfoBeaMJenjang {
/*
{
  "id": 1,
  "jenjang": "Magister",
  "kode_no_induk": "1",
  "is_active": 1,
  "updated_date": "2020-02-10 07:48:18"
} 
*/

  int? id;
  String? jenjang;
  String? kodeNoInduk;
  int? isActive;
  String? updatedDate;

  UserProfileInfoBeaMJenjang({
    this.id,
    this.jenjang,
    this.kodeNoInduk,
    this.isActive,
    this.updatedDate,
  });
  UserProfileInfoBeaMJenjang.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    jenjang = json['jenjang']?.toString();
    kodeNoInduk = json['kode_no_induk']?.toString();
    isActive = json['is_active']?.toInt();
    updatedDate = json['updated_date']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['jenjang'] = jenjang;
    data['kode_no_induk'] = kodeNoInduk;
    data['is_active'] = isActive;
    data['updated_date'] = updatedDate;
    return data;
  }
}

class UserProfileInfoBeaMStatus {
/*
{
  "id": 33,
  "status": "Alumni",
  "tipe_status": "STATUS_BEASISWA",
  "is_active": 1,
  "updated_date": "2021-08-02 16:39:23",
  "status_index": null,
  "value": null
} 
*/

  int? id;
  String? status;
  String? tipeStatus;
  int? isActive;
  String? updatedDate;
  String? statusIndex;
  String? value;

  UserProfileInfoBeaMStatus({
    this.id,
    this.status,
    this.tipeStatus,
    this.isActive,
    this.updatedDate,
    this.statusIndex,
    this.value,
  });
  UserProfileInfoBeaMStatus.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    status = json['status']?.toString();
    tipeStatus = json['tipe_status']?.toString();
    isActive = json['is_active']?.toInt();
    updatedDate = json['updated_date']?.toString();
    statusIndex = json['status_index']?.toString();
    value = json['value']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['status'] = status;
    data['tipe_status'] = tipeStatus;
    data['is_active'] = isActive;
    data['updated_date'] = updatedDate;
    data['status_index'] = statusIndex;
    data['value'] = value;
    return data;
  }
}

class UserProfile {
/*
{
  "kode_registrasi": "0003123/SC/M/2/lpdp2015",
  "nik": "3275063006890015",
  "batch_seleksi": "Tahun 2015 (Tahap 2)",
  "tahun_lolos_seleksi": 2015,
  "no_sk_seleksi": "KEP-44/LPDP/2015",
  "tanggal_sk_seleksi": "2015-06-10 00:00:00",
  "kategori_pembayaran": "Full Scholarship",
  "jenis_beasiswa": "Umum",
  "program_beasiswa": "Beasiswa Reguler",
  "jenis_cofunding": null,
  "jenjang_studi": "Magister",
  "tujuan_beasiswa": "Luar Negeri",
  "nama_lengkap": "M. HASAN SIROJUDDIIN",
  "tempat_lahir": "JAKARTA",
  "tanggal_lahir": "Jun 30 1989 12:00:00:AM",
  "jenis_kelamin": "Laki-Laki",
  "email": "muhammad.hasan.sirojuddiin@gmail.com",
  "kabkota": "KOTA BEKASI",
  "provinsi": "JAWA BARAT",
  "jenis_pekerjaan": "Pegawai Swasta",
  "instansi_kementerian_lembaga": null,
  "bidang_karir": "Swasta",
  "sektor_karir": "Sektor Privat",
  "bidang_keilmuan": "Sains",
  "prodi_asal": "Teknik Elektro dan Informatika",
  "universitas_asal": "Institut Teknologi Bandung",
  "prodi_tujuan_pendaftaran": "Energy Engineering & Management",
  "universitas_tujuan_pendaftaran": "KIT, Karlsruhe Institute of Technology",
  "negara_tujuan_pendaftaran": "Jerman",
  "status_kontrak": "Sudah Kontrak",
  "tahun_kontrak": 2015,
  "no_induk_lpdp": "20150812014171",
  "batch_pk": "36",
  "jenjang_studi_kontrak": "Magister",
  "tujuan_beasiswa_kontrak": "Luar Negeri",
  "universitas_tujuan_kontrak": "The University of Manchester",
  "prodi_tujuan_kontrak": "Renewable Energy and Clean Technology",
  "benua_tujuan_kontrak": "Eropa",
  "negara_tujuan_kontrak": "Inggris",
  "kota_tujuan_kontrak": "Manchester",
  "bidang_keilmuan_kontrak": "Teknik",
  "awal_studi": "Sep 21 2015 12:00:00:AM",
  "akhir_studi": "Sep 16 2016 12:00:00:AM",
  "status_akademik": "Alumni",
  "id": 308,
  "no_sk_penerima_beasiswa": null,
  "tanggal_penerbitan_sp": null,
  "jenis_pengajuan": null,
  "awal_studi_disetujui": "Sep 21 2015 12:00:00:AM",
  "akhir_studi_disetujui": "Sep 16 2016 12:00:00:AM",
  "no_surat_crm": null,
  "updated_date": "2022-02-17 13:30:33",
  "modified_by_id": null,
  "alamat": "Jl. KH A Madani No. 121",
  "nama_bapak": "Dede Dirgahayu",
  "nama_ibu": "Nani Rachmayati",
  "nama_pasangan": "Syifa Mujahidah",
  "status_menikah": null,
  "is_sp_dikembalikan": 0,
  "kabkota_saat_ini": null,
  "alamat_saat_ini": "Jl. KH A Madani No. 121 Rt 08/09, Jatimakmur, Pondok Gede, Bekasi",
  "komponen_biaya_cofunding": null,
  "is_dibuatkan_akun_simonev": 1,
  "negara_tujuan_kontrak_iso_code": "GB",
  "provinsi_asal_iso_code": "indonesia-jawabarat",
  "id_universitas_tujuan_kontrak": 370,
  "id_status_akademik": 6,
  "id_status_kontrak": 38,
  "id_program_beasiswa": 12,
  "id_jenjang_studi": 1,
  "id_tujuan_beasiswa": 2,
  "id_kabkota_asal": 449,
  "no_induk_mahasiswa": null,
  "durasi_studi": 12,
  "frekuensi_dana_hidup": null,
  "bahasa_skor_pendaftaran": "870",
  "bahasa_jenis_tes_pendaftaran": "Inggris (TOEIC)",
  "email_saat_ini": "muhammad.hasan.sirojuddiin@gmail.com",
  "no_hp_saat_ini": "08116145185",
  "awal_studi_2": null,
  "akhir_studi_2": null,
  "awal_studi_3": null,
  "akhir_studi_3": null,
  "awal_studi_4": null,
  "akhir_studi_4": null,
  "sumber_info_durasi_studi": null,
  "catatan_kontrak": null,
  "link_foto": "http://beasiswa.lpdp.kemenkeu.go.id/foto/2018/06/05/44686-M. Hasan Sirojuddiin/511575_Pas Foto Hasan.jpg",
  "tanggal_sk_penerima_beasiswa": null,
  "nama_lengkap_lama": null,
  "id_universitas_tujuan_kontrak_lama": null,
  "prodi_tujuan_kontrak_lama": null,
  "id_tujuan_beasiswa_lama": null,
  "tanggal_sk_penerima_beasiswa_revisi": null,
  "no_sk_penerima_beasiswa_revisi": null,
  "no_sk_penerima_beasiswa_sebelumnya": null,
  "catatan_seleksi": null,
  "nidn": null,
  "nuptk": null,
  "id_sekolah": null,
  "tanggal_sk_berlaku_sejak": null,
  "id_provinsi_saat_ini": null,
  "id_status_beasiswa": 33,
  "id_status_akademik_universitas": null,
  "id_status_pembiayaan": 36,
  "tanggal_deadline_pencarian_loa": null,
  "id_kelas": null,
  "awardee_fakultas": null,
  "awardee_nama_pa": null,
  "awardee_telephone_pa": null,
  "awardee_email_pa": null,
  "awardee_nama_promotor": null,
  "awardee_telephone_promotor": null,
  "awardee_email_promotor": null,
  "awardee_tanggal_masuk": null,
  "awardee_batas_studi": null,
  "awardee_tanggal_lulus": null,
  "awardee_tanggal_yudisium": null,
  "awardee_nomor_ijazah": null,
  "perkembangan_ipk": null,
  "awardee_jurusan_universitas": null,
  "pns_unit_eselon_1": null,
  "pns_unit_eselon_2": null,
  "id_fakultas": null,
  "id_program_studi": null,
  "hak_spp": 2,
  "ishaveloafromseleksi": null,
  "info_bea_m_status": {
    "id": 33,
    "status": "Alumni",
    "tipe_status": "STATUS_BEASISWA",
    "is_active": 1,
    "updated_date": "2021-08-02 16:39:23",
    "status_index": null,
    "value": null
  },
  "info_bea_m_jenjang": {
    "id": 1,
    "jenjang": "Magister",
    "kode_no_induk": "1",
    "is_active": 1,
    "updated_date": "2020-02-10 07:48:18"
  },
  "info_bea_pengayaan_bahasa": null
} 
*/

  String? kodeRegistrasi;
  String? nik;
  String? batchSeleksi;
  int? tahunLolosSeleksi;
  String? noSkSeleksi;
  String? tanggalSkSeleksi;
  String? kategoriPembayaran;
  String? jenisBeasiswa;
  String? programBeasiswa;
  String? jenisCofunding;
  String? jenjangStudi;
  String? tujuanBeasiswa;
  String? namaLengkap;
  String? tempatLahir;
  String? tanggalLahir;
  String? jenisKelamin;
  String? email;
  String? kabkota;
  String? provinsi;
  String? jenisPekerjaan;
  String? instansiKementerianLembaga;
  String? bidangKarir;
  String? sektorKarir;
  String? bidangKeilmuan;
  String? prodiAsal;
  String? universitasAsal;
  String? prodiTujuanPendaftaran;
  String? universitasTujuanPendaftaran;
  String? negaraTujuanPendaftaran;
  String? statusKontrak;
  int? tahunKontrak;
  String? noIndukLpdp;
  String? batchPk;
  String? jenjangStudiKontrak;
  String? tujuanBeasiswaKontrak;
  String? universitasTujuanKontrak;
  String? prodiTujuanKontrak;
  String? benuaTujuanKontrak;
  String? negaraTujuanKontrak;
  String? kotaTujuanKontrak;
  String? bidangKeilmuanKontrak;
  String? awalStudi;
  String? akhirStudi;
  String? statusAkademik;
  int? id;
  String? noSkPenerimaBeasiswa;
  String? tanggalPenerbitanSp;
  String? jenisPengajuan;
  String? awalStudiDisetujui;
  String? akhirStudiDisetujui;
  String? noSuratCrm;
  String? updatedDate;
  String? modifiedById;
  String? alamat;
  String? namaBapak;
  String? namaIbu;
  String? namaPasangan;
  String? statusMenikah;
  int? isSpDikembalikan;
  String? kabkotaSaatIni;
  String? alamatSaatIni;
  String? komponenBiayaCofunding;
  int? isDibuatkanAkunSimonev;
  String? negaraTujuanKontrakIsoCode;
  String? provinsiAsalIsoCode;
  int? idUniversitasTujuanKontrak;
  int? idStatusAkademik;
  int? idStatusKontrak;
  int? idProgramBeasiswa;
  int? idJenjangStudi;
  int? idTujuanBeasiswa;
  int? idKabkotaAsal;
  String? noIndukMahasiswa;
  int? durasiStudi;
  String? frekuensiDanaHidup;
  String? bahasaSkorPendaftaran;
  String? bahasaJenisTesPendaftaran;
  String? emailSaatIni;
  String? noHpSaatIni;
  String? awalStudi_2;
  String? akhirStudi_2;
  String? awalStudi_3;
  String? akhirStudi_3;
  String? awalStudi_4;
  String? akhirStudi_4;
  String? sumberInfoDurasiStudi;
  String? catatanKontrak;
  String? linkFoto;
  String? tanggalSkPenerimaBeasiswa;
  String? namaLengkapLama;
  String? idUniversitasTujuanKontrakLama;
  String? prodiTujuanKontrakLama;
  String? idTujuanBeasiswaLama;
  String? tanggalSkPenerimaBeasiswaRevisi;
  String? noSkPenerimaBeasiswaRevisi;
  String? noSkPenerimaBeasiswaSebelumnya;
  String? catatanSeleksi;
  String? nidn;
  String? nuptk;
  String? idSekolah;
  String? tanggalSkBerlakuSejak;
  String? idProvinsiSaatIni;
  int? idStatusBeasiswa;
  String? idStatusAkademikUniversitas;
  int? idStatusPembiayaan;
  String? tanggalDeadlinePencarianLoa;
  String? idKelas;
  String? awardeeFakultas;
  String? awardeeNamaPa;
  String? awardeeTelephonePa;
  String? awardeeEmailPa;
  String? awardeeNamaPromotor;
  String? awardeeTelephonePromotor;
  String? awardeeEmailPromotor;
  String? awardeeTanggalMasuk;
  String? awardeeBatasStudi;
  String? awardeeTanggalLulus;
  String? awardeeTanggalYudisium;
  String? awardeeNomorIjazah;
  String? perkembanganIpk;
  String? awardeeJurusanUniversitas;
  String? pnsUnitEselon_1;
  String? pnsUnitEselon_2;
  String? idFakultas;
  String? idProgramStudi;
  int? hakSpp;
  String? ishaveloafromseleksi;
  UserProfileInfoBeaMStatus? infoBeaMStatus;
  UserProfileInfoBeaMJenjang? infoBeaMJenjang;
  String? infoBeaPengayaanBahasa;

  UserProfile({
    this.kodeRegistrasi,
    this.nik,
    this.batchSeleksi,
    this.tahunLolosSeleksi,
    this.noSkSeleksi,
    this.tanggalSkSeleksi,
    this.kategoriPembayaran,
    this.jenisBeasiswa,
    this.programBeasiswa,
    this.jenisCofunding,
    this.jenjangStudi,
    this.tujuanBeasiswa,
    this.namaLengkap,
    this.tempatLahir,
    this.tanggalLahir,
    this.jenisKelamin,
    this.email,
    this.kabkota,
    this.provinsi,
    this.jenisPekerjaan,
    this.instansiKementerianLembaga,
    this.bidangKarir,
    this.sektorKarir,
    this.bidangKeilmuan,
    this.prodiAsal,
    this.universitasAsal,
    this.prodiTujuanPendaftaran,
    this.universitasTujuanPendaftaran,
    this.negaraTujuanPendaftaran,
    this.statusKontrak,
    this.tahunKontrak,
    this.noIndukLpdp,
    this.batchPk,
    this.jenjangStudiKontrak,
    this.tujuanBeasiswaKontrak,
    this.universitasTujuanKontrak,
    this.prodiTujuanKontrak,
    this.benuaTujuanKontrak,
    this.negaraTujuanKontrak,
    this.kotaTujuanKontrak,
    this.bidangKeilmuanKontrak,
    this.awalStudi,
    this.akhirStudi,
    this.statusAkademik,
    this.id,
    this.noSkPenerimaBeasiswa,
    this.tanggalPenerbitanSp,
    this.jenisPengajuan,
    this.awalStudiDisetujui,
    this.akhirStudiDisetujui,
    this.noSuratCrm,
    this.updatedDate,
    this.modifiedById,
    this.alamat,
    this.namaBapak,
    this.namaIbu,
    this.namaPasangan,
    this.statusMenikah,
    this.isSpDikembalikan,
    this.kabkotaSaatIni,
    this.alamatSaatIni,
    this.komponenBiayaCofunding,
    this.isDibuatkanAkunSimonev,
    this.negaraTujuanKontrakIsoCode,
    this.provinsiAsalIsoCode,
    this.idUniversitasTujuanKontrak,
    this.idStatusAkademik,
    this.idStatusKontrak,
    this.idProgramBeasiswa,
    this.idJenjangStudi,
    this.idTujuanBeasiswa,
    this.idKabkotaAsal,
    this.noIndukMahasiswa,
    this.durasiStudi,
    this.frekuensiDanaHidup,
    this.bahasaSkorPendaftaran,
    this.bahasaJenisTesPendaftaran,
    this.emailSaatIni,
    this.noHpSaatIni,
    this.awalStudi_2,
    this.akhirStudi_2,
    this.awalStudi_3,
    this.akhirStudi_3,
    this.awalStudi_4,
    this.akhirStudi_4,
    this.sumberInfoDurasiStudi,
    this.catatanKontrak,
    this.linkFoto,
    this.tanggalSkPenerimaBeasiswa,
    this.namaLengkapLama,
    this.idUniversitasTujuanKontrakLama,
    this.prodiTujuanKontrakLama,
    this.idTujuanBeasiswaLama,
    this.tanggalSkPenerimaBeasiswaRevisi,
    this.noSkPenerimaBeasiswaRevisi,
    this.noSkPenerimaBeasiswaSebelumnya,
    this.catatanSeleksi,
    this.nidn,
    this.nuptk,
    this.idSekolah,
    this.tanggalSkBerlakuSejak,
    this.idProvinsiSaatIni,
    this.idStatusBeasiswa,
    this.idStatusAkademikUniversitas,
    this.idStatusPembiayaan,
    this.tanggalDeadlinePencarianLoa,
    this.idKelas,
    this.awardeeFakultas,
    this.awardeeNamaPa,
    this.awardeeTelephonePa,
    this.awardeeEmailPa,
    this.awardeeNamaPromotor,
    this.awardeeTelephonePromotor,
    this.awardeeEmailPromotor,
    this.awardeeTanggalMasuk,
    this.awardeeBatasStudi,
    this.awardeeTanggalLulus,
    this.awardeeTanggalYudisium,
    this.awardeeNomorIjazah,
    this.perkembanganIpk,
    this.awardeeJurusanUniversitas,
    this.pnsUnitEselon_1,
    this.pnsUnitEselon_2,
    this.idFakultas,
    this.idProgramStudi,
    this.hakSpp,
    this.ishaveloafromseleksi,
    this.infoBeaMStatus,
    this.infoBeaMJenjang,
    this.infoBeaPengayaanBahasa,
  });
  UserProfile.fromJson(Map<String, dynamic> json) {
    kodeRegistrasi = json['kode_registrasi']?.toString();
    nik = json['nik']?.toString();
    batchSeleksi = json['batch_seleksi']?.toString();
    tahunLolosSeleksi = json['tahun_lolos_seleksi']?.toInt();
    noSkSeleksi = json['no_sk_seleksi']?.toString();
    tanggalSkSeleksi = json['tanggal_sk_seleksi']?.toString();
    kategoriPembayaran = json['kategori_pembayaran']?.toString();
    jenisBeasiswa = json['jenis_beasiswa']?.toString();
    programBeasiswa = json['program_beasiswa']?.toString();
    jenisCofunding = json['jenis_cofunding']?.toString();
    jenjangStudi = json['jenjang_studi']?.toString();
    tujuanBeasiswa = json['tujuan_beasiswa']?.toString();
    namaLengkap = json['nama_lengkap']?.toString();
    tempatLahir = json['tempat_lahir']?.toString();
    tanggalLahir = json['tanggal_lahir']?.toString();
    jenisKelamin = json['jenis_kelamin']?.toString();
    email = json['email']?.toString();
    kabkota = json['kabkota']?.toString();
    provinsi = json['provinsi']?.toString();
    jenisPekerjaan = json['jenis_pekerjaan']?.toString();
    instansiKementerianLembaga = json['instansi_kementerian_lembaga']?.toString();
    bidangKarir = json['bidang_karir']?.toString();
    sektorKarir = json['sektor_karir']?.toString();
    bidangKeilmuan = json['bidang_keilmuan']?.toString();
    prodiAsal = json['prodi_asal']?.toString();
    universitasAsal = json['universitas_asal']?.toString();
    prodiTujuanPendaftaran = json['prodi_tujuan_pendaftaran']?.toString();
    universitasTujuanPendaftaran = json['universitas_tujuan_pendaftaran']?.toString();
    negaraTujuanPendaftaran = json['negara_tujuan_pendaftaran']?.toString();
    statusKontrak = json['status_kontrak']?.toString();
    tahunKontrak = json['tahun_kontrak']?.toInt();
    noIndukLpdp = json['no_induk_lpdp']?.toString();
    batchPk = json['batch_pk']?.toString();
    jenjangStudiKontrak = json['jenjang_studi_kontrak']?.toString();
    tujuanBeasiswaKontrak = json['tujuan_beasiswa_kontrak']?.toString();
    universitasTujuanKontrak = json['universitas_tujuan_kontrak']?.toString();
    prodiTujuanKontrak = json['prodi_tujuan_kontrak']?.toString();
    benuaTujuanKontrak = json['benua_tujuan_kontrak']?.toString();
    negaraTujuanKontrak = json['negara_tujuan_kontrak']?.toString();
    kotaTujuanKontrak = json['kota_tujuan_kontrak']?.toString();
    bidangKeilmuanKontrak = json['bidang_keilmuan_kontrak']?.toString();
    awalStudi = json['awal_studi']?.toString();
    akhirStudi = json['akhir_studi']?.toString();
    statusAkademik = json['status_akademik']?.toString();
    id = json['id']?.toInt();
    noSkPenerimaBeasiswa = json['no_sk_penerima_beasiswa']?.toString();
    tanggalPenerbitanSp = json['tanggal_penerbitan_sp']?.toString();
    jenisPengajuan = json['jenis_pengajuan']?.toString();
    awalStudiDisetujui = json['awal_studi_disetujui']?.toString();
    akhirStudiDisetujui = json['akhir_studi_disetujui']?.toString();
    noSuratCrm = json['no_surat_crm']?.toString();
    updatedDate = json['updated_date']?.toString();
    modifiedById = json['modified_by_id']?.toString();
    alamat = json['alamat']?.toString();
    namaBapak = json['nama_bapak']?.toString();
    namaIbu = json['nama_ibu']?.toString();
    namaPasangan = json['nama_pasangan']?.toString();
    statusMenikah = json['status_menikah']?.toString();
    isSpDikembalikan = json['is_sp_dikembalikan']?.toInt();
    kabkotaSaatIni = json['kabkota_saat_ini']?.toString();
    alamatSaatIni = json['alamat_saat_ini']?.toString();
    komponenBiayaCofunding = json['komponen_biaya_cofunding']?.toString();
    isDibuatkanAkunSimonev = json['is_dibuatkan_akun_simonev']?.toInt();
    negaraTujuanKontrakIsoCode = json['negara_tujuan_kontrak_iso_code']?.toString();
    provinsiAsalIsoCode = json['provinsi_asal_iso_code']?.toString();
    idUniversitasTujuanKontrak = json['id_universitas_tujuan_kontrak']?.toInt();
    idStatusAkademik = json['id_status_akademik']?.toInt();
    idStatusKontrak = json['id_status_kontrak']?.toInt();
    idProgramBeasiswa = json['id_program_beasiswa']?.toInt();
    idJenjangStudi = json['id_jenjang_studi']?.toInt();
    idTujuanBeasiswa = json['id_tujuan_beasiswa']?.toInt();
    idKabkotaAsal = json['id_kabkota_asal']?.toInt();
    noIndukMahasiswa = json['no_induk_mahasiswa']?.toString();
    durasiStudi = json['durasi_studi']?.toInt();
    frekuensiDanaHidup = json['frekuensi_dana_hidup']?.toString();
    bahasaSkorPendaftaran = json['bahasa_skor_pendaftaran']?.toString();
    bahasaJenisTesPendaftaran = json['bahasa_jenis_tes_pendaftaran']?.toString();
    emailSaatIni = json['email_saat_ini']?.toString();
    noHpSaatIni = json['no_hp_saat_ini']?.toString();
    awalStudi_2 = json['awal_studi_2']?.toString();
    akhirStudi_2 = json['akhir_studi_2']?.toString();
    awalStudi_3 = json['awal_studi_3']?.toString();
    akhirStudi_3 = json['akhir_studi_3']?.toString();
    awalStudi_4 = json['awal_studi_4']?.toString();
    akhirStudi_4 = json['akhir_studi_4']?.toString();
    sumberInfoDurasiStudi = json['sumber_info_durasi_studi']?.toString();
    catatanKontrak = json['catatan_kontrak']?.toString();
    linkFoto = json['link_foto']?.toString();
    tanggalSkPenerimaBeasiswa = json['tanggal_sk_penerima_beasiswa']?.toString();
    namaLengkapLama = json['nama_lengkap_lama']?.toString();
    idUniversitasTujuanKontrakLama = json['id_universitas_tujuan_kontrak_lama']?.toString();
    prodiTujuanKontrakLama = json['prodi_tujuan_kontrak_lama']?.toString();
    idTujuanBeasiswaLama = json['id_tujuan_beasiswa_lama']?.toString();
    tanggalSkPenerimaBeasiswaRevisi = json['tanggal_sk_penerima_beasiswa_revisi']?.toString();
    noSkPenerimaBeasiswaRevisi = json['no_sk_penerima_beasiswa_revisi']?.toString();
    noSkPenerimaBeasiswaSebelumnya = json['no_sk_penerima_beasiswa_sebelumnya']?.toString();
    catatanSeleksi = json['catatan_seleksi']?.toString();
    nidn = json['nidn']?.toString();
    nuptk = json['nuptk']?.toString();
    idSekolah = json['id_sekolah']?.toString();
    tanggalSkBerlakuSejak = json['tanggal_sk_berlaku_sejak']?.toString();
    idProvinsiSaatIni = json['id_provinsi_saat_ini']?.toString();
    idStatusBeasiswa = json['id_status_beasiswa']?.toInt();
    idStatusAkademikUniversitas = json['id_status_akademik_universitas']?.toString();
    idStatusPembiayaan = json['id_status_pembiayaan']?.toInt();
    tanggalDeadlinePencarianLoa = json['tanggal_deadline_pencarian_loa']?.toString();
    idKelas = json['id_kelas']?.toString();
    awardeeFakultas = json['awardee_fakultas']?.toString();
    awardeeNamaPa = json['awardee_nama_pa']?.toString();
    awardeeTelephonePa = json['awardee_telephone_pa']?.toString();
    awardeeEmailPa = json['awardee_email_pa']?.toString();
    awardeeNamaPromotor = json['awardee_nama_promotor']?.toString();
    awardeeTelephonePromotor = json['awardee_telephone_promotor']?.toString();
    awardeeEmailPromotor = json['awardee_email_promotor']?.toString();
    awardeeTanggalMasuk = json['awardee_tanggal_masuk']?.toString();
    awardeeBatasStudi = json['awardee_batas_studi']?.toString();
    awardeeTanggalLulus = json['awardee_tanggal_lulus']?.toString();
    awardeeTanggalYudisium = json['awardee_tanggal_yudisium']?.toString();
    awardeeNomorIjazah = json['awardee_nomor_ijazah']?.toString();
    perkembanganIpk = json['perkembangan_ipk']?.toString();
    awardeeJurusanUniversitas = json['awardee_jurusan_universitas']?.toString();
    pnsUnitEselon_1 = json['pns_unit_eselon_1']?.toString();
    pnsUnitEselon_2 = json['pns_unit_eselon_2']?.toString();
    idFakultas = json['id_fakultas']?.toString();
    idProgramStudi = json['id_program_studi']?.toString();
    hakSpp = json['hak_spp']?.toInt();
    ishaveloafromseleksi = json['ishaveloafromseleksi']?.toString();
    infoBeaMStatus = (json['info_bea_m_status'] != null) ? UserProfileInfoBeaMStatus.fromJson(json['info_bea_m_status']) : null;
    infoBeaMJenjang = (json['info_bea_m_jenjang'] != null) ? UserProfileInfoBeaMJenjang.fromJson(json['info_bea_m_jenjang']) : null;
    infoBeaPengayaanBahasa = json['info_bea_pengayaan_bahasa']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['kode_registrasi'] = kodeRegistrasi;
    data['nik'] = nik;
    data['batch_seleksi'] = batchSeleksi;
    data['tahun_lolos_seleksi'] = tahunLolosSeleksi;
    data['no_sk_seleksi'] = noSkSeleksi;
    data['tanggal_sk_seleksi'] = tanggalSkSeleksi;
    data['kategori_pembayaran'] = kategoriPembayaran;
    data['jenis_beasiswa'] = jenisBeasiswa;
    data['program_beasiswa'] = programBeasiswa;
    data['jenis_cofunding'] = jenisCofunding;
    data['jenjang_studi'] = jenjangStudi;
    data['tujuan_beasiswa'] = tujuanBeasiswa;
    data['nama_lengkap'] = namaLengkap;
    data['tempat_lahir'] = tempatLahir;
    data['tanggal_lahir'] = tanggalLahir;
    data['jenis_kelamin'] = jenisKelamin;
    data['email'] = email;
    data['kabkota'] = kabkota;
    data['provinsi'] = provinsi;
    data['jenis_pekerjaan'] = jenisPekerjaan;
    data['instansi_kementerian_lembaga'] = instansiKementerianLembaga;
    data['bidang_karir'] = bidangKarir;
    data['sektor_karir'] = sektorKarir;
    data['bidang_keilmuan'] = bidangKeilmuan;
    data['prodi_asal'] = prodiAsal;
    data['universitas_asal'] = universitasAsal;
    data['prodi_tujuan_pendaftaran'] = prodiTujuanPendaftaran;
    data['universitas_tujuan_pendaftaran'] = universitasTujuanPendaftaran;
    data['negara_tujuan_pendaftaran'] = negaraTujuanPendaftaran;
    data['status_kontrak'] = statusKontrak;
    data['tahun_kontrak'] = tahunKontrak;
    data['no_induk_lpdp'] = noIndukLpdp;
    data['batch_pk'] = batchPk;
    data['jenjang_studi_kontrak'] = jenjangStudiKontrak;
    data['tujuan_beasiswa_kontrak'] = tujuanBeasiswaKontrak;
    data['universitas_tujuan_kontrak'] = universitasTujuanKontrak;
    data['prodi_tujuan_kontrak'] = prodiTujuanKontrak;
    data['benua_tujuan_kontrak'] = benuaTujuanKontrak;
    data['negara_tujuan_kontrak'] = negaraTujuanKontrak;
    data['kota_tujuan_kontrak'] = kotaTujuanKontrak;
    data['bidang_keilmuan_kontrak'] = bidangKeilmuanKontrak;
    data['awal_studi'] = awalStudi;
    data['akhir_studi'] = akhirStudi;
    data['status_akademik'] = statusAkademik;
    data['id'] = id;
    data['no_sk_penerima_beasiswa'] = noSkPenerimaBeasiswa;
    data['tanggal_penerbitan_sp'] = tanggalPenerbitanSp;
    data['jenis_pengajuan'] = jenisPengajuan;
    data['awal_studi_disetujui'] = awalStudiDisetujui;
    data['akhir_studi_disetujui'] = akhirStudiDisetujui;
    data['no_surat_crm'] = noSuratCrm;
    data['updated_date'] = updatedDate;
    data['modified_by_id'] = modifiedById;
    data['alamat'] = alamat;
    data['nama_bapak'] = namaBapak;
    data['nama_ibu'] = namaIbu;
    data['nama_pasangan'] = namaPasangan;
    data['status_menikah'] = statusMenikah;
    data['is_sp_dikembalikan'] = isSpDikembalikan;
    data['kabkota_saat_ini'] = kabkotaSaatIni;
    data['alamat_saat_ini'] = alamatSaatIni;
    data['komponen_biaya_cofunding'] = komponenBiayaCofunding;
    data['is_dibuatkan_akun_simonev'] = isDibuatkanAkunSimonev;
    data['negara_tujuan_kontrak_iso_code'] = negaraTujuanKontrakIsoCode;
    data['provinsi_asal_iso_code'] = provinsiAsalIsoCode;
    data['id_universitas_tujuan_kontrak'] = idUniversitasTujuanKontrak;
    data['id_status_akademik'] = idStatusAkademik;
    data['id_status_kontrak'] = idStatusKontrak;
    data['id_program_beasiswa'] = idProgramBeasiswa;
    data['id_jenjang_studi'] = idJenjangStudi;
    data['id_tujuan_beasiswa'] = idTujuanBeasiswa;
    data['id_kabkota_asal'] = idKabkotaAsal;
    data['no_induk_mahasiswa'] = noIndukMahasiswa;
    data['durasi_studi'] = durasiStudi;
    data['frekuensi_dana_hidup'] = frekuensiDanaHidup;
    data['bahasa_skor_pendaftaran'] = bahasaSkorPendaftaran;
    data['bahasa_jenis_tes_pendaftaran'] = bahasaJenisTesPendaftaran;
    data['email_saat_ini'] = emailSaatIni;
    data['no_hp_saat_ini'] = noHpSaatIni;
    data['awal_studi_2'] = awalStudi_2;
    data['akhir_studi_2'] = akhirStudi_2;
    data['awal_studi_3'] = awalStudi_3;
    data['akhir_studi_3'] = akhirStudi_3;
    data['awal_studi_4'] = awalStudi_4;
    data['akhir_studi_4'] = akhirStudi_4;
    data['sumber_info_durasi_studi'] = sumberInfoDurasiStudi;
    data['catatan_kontrak'] = catatanKontrak;
    data['link_foto'] = linkFoto;
    data['tanggal_sk_penerima_beasiswa'] = tanggalSkPenerimaBeasiswa;
    data['nama_lengkap_lama'] = namaLengkapLama;
    data['id_universitas_tujuan_kontrak_lama'] = idUniversitasTujuanKontrakLama;
    data['prodi_tujuan_kontrak_lama'] = prodiTujuanKontrakLama;
    data['id_tujuan_beasiswa_lama'] = idTujuanBeasiswaLama;
    data['tanggal_sk_penerima_beasiswa_revisi'] = tanggalSkPenerimaBeasiswaRevisi;
    data['no_sk_penerima_beasiswa_revisi'] = noSkPenerimaBeasiswaRevisi;
    data['no_sk_penerima_beasiswa_sebelumnya'] = noSkPenerimaBeasiswaSebelumnya;
    data['catatan_seleksi'] = catatanSeleksi;
    data['nidn'] = nidn;
    data['nuptk'] = nuptk;
    data['id_sekolah'] = idSekolah;
    data['tanggal_sk_berlaku_sejak'] = tanggalSkBerlakuSejak;
    data['id_provinsi_saat_ini'] = idProvinsiSaatIni;
    data['id_status_beasiswa'] = idStatusBeasiswa;
    data['id_status_akademik_universitas'] = idStatusAkademikUniversitas;
    data['id_status_pembiayaan'] = idStatusPembiayaan;
    data['tanggal_deadline_pencarian_loa'] = tanggalDeadlinePencarianLoa;
    data['id_kelas'] = idKelas;
    data['awardee_fakultas'] = awardeeFakultas;
    data['awardee_nama_pa'] = awardeeNamaPa;
    data['awardee_telephone_pa'] = awardeeTelephonePa;
    data['awardee_email_pa'] = awardeeEmailPa;
    data['awardee_nama_promotor'] = awardeeNamaPromotor;
    data['awardee_telephone_promotor'] = awardeeTelephonePromotor;
    data['awardee_email_promotor'] = awardeeEmailPromotor;
    data['awardee_tanggal_masuk'] = awardeeTanggalMasuk;
    data['awardee_batas_studi'] = awardeeBatasStudi;
    data['awardee_tanggal_lulus'] = awardeeTanggalLulus;
    data['awardee_tanggal_yudisium'] = awardeeTanggalYudisium;
    data['awardee_nomor_ijazah'] = awardeeNomorIjazah;
    data['perkembangan_ipk'] = perkembanganIpk;
    data['awardee_jurusan_universitas'] = awardeeJurusanUniversitas;
    data['pns_unit_eselon_1'] = pnsUnitEselon_1;
    data['pns_unit_eselon_2'] = pnsUnitEselon_2;
    data['id_fakultas'] = idFakultas;
    data['id_program_studi'] = idProgramStudi;
    data['hak_spp'] = hakSpp;
    data['ishaveloafromseleksi'] = ishaveloafromseleksi;
    if (infoBeaMStatus != null) {
      data['info_bea_m_status'] = infoBeaMStatus!.toJson();
    }
    if (infoBeaMJenjang != null) {
      data['info_bea_m_jenjang'] = infoBeaMJenjang!.toJson();
    }
    data['info_bea_pengayaan_bahasa'] = infoBeaPengayaanBahasa;
    return data;
  }
}
