///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class UserFunding {
/*
{
  "id": 0,
  "koderegistrasi": "0007713/TRP/M/19/lpdp2023",
  "costitem": 2,
  "currency": 70,
  "requestamount": null,
  "requestamountidr": 25000000,
  "bankaccount": 1,
  "jenispendanaanbank": "Syariah",
  "paymentdesc": "asddas",
  "remarks": "dasdda",
  "lampiran": "Dokumen/FundRequest/aeb57cbc-1b69-4d2a-81d5-da338784d3d5/9e052dc2cc3c4e38baddd3a855229305_FileLampiran.pdf",
  "tglpengajuan": "2023-11-22 20:14:08",
  "iscard": null,
  "tglupdate": "2023-11-22 20:14:08",
  "approvedamount": null,
  "approvedamountidr": null,
  "catatan": null,
  "uraianpembayaran": null,
  "remarksverify": null,
  "awalperiode": null,
  "akhirperiode": null,
  "status": 1,
  "userverify": null,
  "dateverify": null,
  "nospp": null,
  "nominativeid": null,
  "dkuverify": null,
  "tgldkuverify": null,
  "statusdkuverify": null,
  "catatandku": null,
  "tl": null,
  "tgltl": null,
  "catatanspb": null,
  "kasubdivverify": null,
  "tglkasubdivverify": null,
  "statuskasubdivverify": null,
  "catatankasubdiv": null,
  "catatanspbkasubdiv": null,
  "tanggallapordirikjri": null,
  "nomorkkkel1": null,
  "nomorkkkel2": null,
  "nikkel1": null,
  "nikkel2": null,
  "namakel1": null,
  "namakel2": null,
  "tgllahirkel1": null,
  "tgllahirkel2": null,
  "tglkedatangan": null,
  "bulanpengajuan": "1,2,3,4,5,6",
  "tglkeberangkatan": null,
  "bandaraasal": null,
  "bandaratujuan": null,
  "pathtiket": null,
  "kirimtagihan": null,
  "nomorvisa": null,
  "nomorpaspor": null,
  "durasitinggalstart": null,
  "durasitinggalend": null,
  "createdbyrole": "PB",
  "kurs": null,
  "isnp": null,
  "namabank": "Bank Syariah Indonesia",
  "alamatbank": "Jl. Kaliurang KM.5 No.35, Yogyakarta",
  "atasnama": "AFIFAH SHAFARI ZULIANSYAH",
  "nomorrekening": "7147719048",
  "swiftcode": "BSMDIDJA",
  "iban": null,
  "billingidspp": null,
  "judultesisdisertasi": null,
  "labnonlab": null,
  "namadosenpembimbing": null,
  "emaildosenpembimbing": null,
  "tanggallulussempro": null,
  "tempatpengambilandata": null,
  "fullcoursework": null,
  "skemapencairandana": null,
  "sptjm": null,
  "beritaacarasidangseminar": null,
  "lembarpengesahanproposaltesisdisertasi": null,
  "penetapanpenelitian": null,
  "suratketeranganbukanfullcoursework": null,
  "proposaltesisdisertasi": null,
  "pernyataandospemrabdisetujui": null,
  "suratketerangantidakdidanaiuniv": null,
  "pernyataantanggungjawabbelanja": null,
  "rabaccdospem": null,
  "dpcatatanspba": null,
  "dpcatatanspbb": null,
  "dpcatatanspbc": null,
  "dpcatatankasubdiva": null,
  "dpcatatankasubdivb": null,
  "komphabispakai": null,
  "komppengadaan": null,
  "komphonor": null,
  "komplainlain": null,
  "waktupengambilandata": null,
  "spkverify": null,
  "tglspkverify": null,
  "tipependanaan": "Dana SPP",
  "id_fundrequest": null,
  "perkuliahanbukanfullcoursework": null,
  "bukutabungan": "Dokumen/BankAccount/aeb57cbc-1b69-4d2a-81d5-da338784d3d5/183fb9794163430abeec1856a992b430_FileBankDN.pdf",
  "tgldiprosesbank": null,
  "updatedby": null,
  "dpcatatantolakawardee": null,
  "matauangbank": "IDR",
  "statuspayment": null,
  "nominativeiderpdelete": null,
  "fund_request_cost_item": null,
  "fund_request_status": null
} 
*/

  int? id;
  String? koderegistrasi;
  int? costitem;
  int? currency;
  String? requestamount;
  int? requestamountidr;
  int? bankaccount;
  String? jenispendanaanbank;
  String? paymentdesc;
  String? remarks;
  String? lampiran;
  String? tglpengajuan;
  String? iscard;
  String? tglupdate;
  String? approvedamount;
  String? approvedamountidr;
  String? catatan;
  String? uraianpembayaran;
  String? remarksverify;
  String? awalperiode;
  String? akhirperiode;
  int? status;
  String? userverify;
  String? dateverify;
  String? nospp;
  String? nominativeid;
  String? dkuverify;
  String? tgldkuverify;
  String? statusdkuverify;
  String? catatandku;
  String? tl;
  String? tgltl;
  String? catatanspb;
  String? kasubdivverify;
  String? tglkasubdivverify;
  String? statuskasubdivverify;
  String? catatankasubdiv;
  String? catatanspbkasubdiv;
  String? tanggallapordirikjri;
  String? nomorkkkel1;
  String? nomorkkkel2;
  String? nikkel1;
  String? nikkel2;
  String? namakel1;
  String? namakel2;
  String? tgllahirkel1;
  String? tgllahirkel2;
  String? tglkedatangan;
  String? bulanpengajuan;
  String? tglkeberangkatan;
  String? bandaraasal;
  String? bandaratujuan;
  String? pathtiket;
  String? kirimtagihan;
  String? nomorvisa;
  String? nomorpaspor;
  String? durasitinggalstart;
  String? durasitinggalend;
  String? createdbyrole;
  String? kurs;
  String? isnp;
  String? namabank;
  String? alamatbank;
  String? atasnama;
  String? nomorrekening;
  String? swiftcode;
  String? iban;
  String? billingidspp;
  String? judultesisdisertasi;
  String? labnonlab;
  String? namadosenpembimbing;
  String? emaildosenpembimbing;
  String? tanggallulussempro;
  String? tempatpengambilandata;
  String? fullcoursework;
  String? skemapencairandana;
  String? sptjm;
  String? beritaacarasidangseminar;
  String? lembarpengesahanproposaltesisdisertasi;
  String? penetapanpenelitian;
  String? suratketeranganbukanfullcoursework;
  String? proposaltesisdisertasi;
  String? pernyataandospemrabdisetujui;
  String? suratketerangantidakdidanaiuniv;
  String? pernyataantanggungjawabbelanja;
  String? rabaccdospem;
  String? dpcatatanspba;
  String? dpcatatanspbb;
  String? dpcatatanspbc;
  String? dpcatatankasubdiva;
  String? dpcatatankasubdivb;
  String? komphabispakai;
  String? komppengadaan;
  String? komphonor;
  String? komplainlain;
  String? waktupengambilandata;
  String? spkverify;
  String? tglspkverify;
  String? tipependanaan;
  String? idFundrequest;
  String? perkuliahanbukanfullcoursework;
  String? bukutabungan;
  String? tgldiprosesbank;
  String? updatedby;
  String? dpcatatantolakawardee;
  String? matauangbank;
  String? statuspayment;
  String? nominativeiderpdelete;
  String? fundRequestCostItem;
  String? fundRequestStatus;

  UserFunding({
    this.id,
    this.koderegistrasi,
    this.costitem,
    this.currency,
    this.requestamount,
    this.requestamountidr,
    this.bankaccount,
    this.jenispendanaanbank,
    this.paymentdesc,
    this.remarks,
    this.lampiran,
    this.tglpengajuan,
    this.iscard,
    this.tglupdate,
    this.approvedamount,
    this.approvedamountidr,
    this.catatan,
    this.uraianpembayaran,
    this.remarksverify,
    this.awalperiode,
    this.akhirperiode,
    this.status,
    this.userverify,
    this.dateverify,
    this.nospp,
    this.nominativeid,
    this.dkuverify,
    this.tgldkuverify,
    this.statusdkuverify,
    this.catatandku,
    this.tl,
    this.tgltl,
    this.catatanspb,
    this.kasubdivverify,
    this.tglkasubdivverify,
    this.statuskasubdivverify,
    this.catatankasubdiv,
    this.catatanspbkasubdiv,
    this.tanggallapordirikjri,
    this.nomorkkkel1,
    this.nomorkkkel2,
    this.nikkel1,
    this.nikkel2,
    this.namakel1,
    this.namakel2,
    this.tgllahirkel1,
    this.tgllahirkel2,
    this.tglkedatangan,
    this.bulanpengajuan,
    this.tglkeberangkatan,
    this.bandaraasal,
    this.bandaratujuan,
    this.pathtiket,
    this.kirimtagihan,
    this.nomorvisa,
    this.nomorpaspor,
    this.durasitinggalstart,
    this.durasitinggalend,
    this.createdbyrole,
    this.kurs,
    this.isnp,
    this.namabank,
    this.alamatbank,
    this.atasnama,
    this.nomorrekening,
    this.swiftcode,
    this.iban,
    this.billingidspp,
    this.judultesisdisertasi,
    this.labnonlab,
    this.namadosenpembimbing,
    this.emaildosenpembimbing,
    this.tanggallulussempro,
    this.tempatpengambilandata,
    this.fullcoursework,
    this.skemapencairandana,
    this.sptjm,
    this.beritaacarasidangseminar,
    this.lembarpengesahanproposaltesisdisertasi,
    this.penetapanpenelitian,
    this.suratketeranganbukanfullcoursework,
    this.proposaltesisdisertasi,
    this.pernyataandospemrabdisetujui,
    this.suratketerangantidakdidanaiuniv,
    this.pernyataantanggungjawabbelanja,
    this.rabaccdospem,
    this.dpcatatanspba,
    this.dpcatatanspbb,
    this.dpcatatanspbc,
    this.dpcatatankasubdiva,
    this.dpcatatankasubdivb,
    this.komphabispakai,
    this.komppengadaan,
    this.komphonor,
    this.komplainlain,
    this.waktupengambilandata,
    this.spkverify,
    this.tglspkverify,
    this.tipependanaan,
    this.idFundrequest,
    this.perkuliahanbukanfullcoursework,
    this.bukutabungan,
    this.tgldiprosesbank,
    this.updatedby,
    this.dpcatatantolakawardee,
    this.matauangbank,
    this.statuspayment,
    this.nominativeiderpdelete,
    this.fundRequestCostItem,
    this.fundRequestStatus,
  });
  UserFunding.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    koderegistrasi = json['koderegistrasi']?.toString();
    costitem = json['costitem']?.toInt();
    currency = json['currency']?.toInt();
    requestamount = json['requestamount']?.toString();
    requestamountidr = json['requestamountidr']?.toInt();
    bankaccount = json['bankaccount']?.toInt();
    jenispendanaanbank = json['jenispendanaanbank']?.toString();
    paymentdesc = json['paymentdesc']?.toString();
    remarks = json['remarks']?.toString();
    lampiran = json['lampiran']?.toString();
    tglpengajuan = json['tglpengajuan']?.toString();
    iscard = json['iscard']?.toString();
    tglupdate = json['tglupdate']?.toString();
    approvedamount = json['approvedamount']?.toString();
    approvedamountidr = json['approvedamountidr']?.toString();
    catatan = json['catatan']?.toString();
    uraianpembayaran = json['uraianpembayaran']?.toString();
    remarksverify = json['remarksverify']?.toString();
    awalperiode = json['awalperiode']?.toString();
    akhirperiode = json['akhirperiode']?.toString();
    status = json['status']?.toInt();
    userverify = json['userverify']?.toString();
    dateverify = json['dateverify']?.toString();
    nospp = json['nospp']?.toString();
    nominativeid = json['nominativeid']?.toString();
    dkuverify = json['dkuverify']?.toString();
    tgldkuverify = json['tgldkuverify']?.toString();
    statusdkuverify = json['statusdkuverify']?.toString();
    catatandku = json['catatandku']?.toString();
    tl = json['tl']?.toString();
    tgltl = json['tgltl']?.toString();
    catatanspb = json['catatanspb']?.toString();
    kasubdivverify = json['kasubdivverify']?.toString();
    tglkasubdivverify = json['tglkasubdivverify']?.toString();
    statuskasubdivverify = json['statuskasubdivverify']?.toString();
    catatankasubdiv = json['catatankasubdiv']?.toString();
    catatanspbkasubdiv = json['catatanspbkasubdiv']?.toString();
    tanggallapordirikjri = json['tanggallapordirikjri']?.toString();
    nomorkkkel1 = json['nomorkkkel1']?.toString();
    nomorkkkel2 = json['nomorkkkel2']?.toString();
    nikkel1 = json['nikkel1']?.toString();
    nikkel2 = json['nikkel2']?.toString();
    namakel1 = json['namakel1']?.toString();
    namakel2 = json['namakel2']?.toString();
    tgllahirkel1 = json['tgllahirkel1']?.toString();
    tgllahirkel2 = json['tgllahirkel2']?.toString();
    tglkedatangan = json['tglkedatangan']?.toString();
    bulanpengajuan = json['bulanpengajuan']?.toString();
    tglkeberangkatan = json['tglkeberangkatan']?.toString();
    bandaraasal = json['bandaraasal']?.toString();
    bandaratujuan = json['bandaratujuan']?.toString();
    pathtiket = json['pathtiket']?.toString();
    kirimtagihan = json['kirimtagihan']?.toString();
    nomorvisa = json['nomorvisa']?.toString();
    nomorpaspor = json['nomorpaspor']?.toString();
    durasitinggalstart = json['durasitinggalstart']?.toString();
    durasitinggalend = json['durasitinggalend']?.toString();
    createdbyrole = json['createdbyrole']?.toString();
    kurs = json['kurs']?.toString();
    isnp = json['isnp']?.toString();
    namabank = json['namabank']?.toString();
    alamatbank = json['alamatbank']?.toString();
    atasnama = json['atasnama']?.toString();
    nomorrekening = json['nomorrekening']?.toString();
    swiftcode = json['swiftcode']?.toString();
    iban = json['iban']?.toString();
    billingidspp = json['billingidspp']?.toString();
    judultesisdisertasi = json['judultesisdisertasi']?.toString();
    labnonlab = json['labnonlab']?.toString();
    namadosenpembimbing = json['namadosenpembimbing']?.toString();
    emaildosenpembimbing = json['emaildosenpembimbing']?.toString();
    tanggallulussempro = json['tanggallulussempro']?.toString();
    tempatpengambilandata = json['tempatpengambilandata']?.toString();
    fullcoursework = json['fullcoursework']?.toString();
    skemapencairandana = json['skemapencairandana']?.toString();
    sptjm = json['sptjm']?.toString();
    beritaacarasidangseminar = json['beritaacarasidangseminar']?.toString();
    lembarpengesahanproposaltesisdisertasi = json['lembarpengesahanproposaltesisdisertasi']?.toString();
    penetapanpenelitian = json['penetapanpenelitian']?.toString();
    suratketeranganbukanfullcoursework = json['suratketeranganbukanfullcoursework']?.toString();
    proposaltesisdisertasi = json['proposaltesisdisertasi']?.toString();
    pernyataandospemrabdisetujui = json['pernyataandospemrabdisetujui']?.toString();
    suratketerangantidakdidanaiuniv = json['suratketerangantidakdidanaiuniv']?.toString();
    pernyataantanggungjawabbelanja = json['pernyataantanggungjawabbelanja']?.toString();
    rabaccdospem = json['rabaccdospem']?.toString();
    dpcatatanspba = json['dpcatatanspba']?.toString();
    dpcatatanspbb = json['dpcatatanspbb']?.toString();
    dpcatatanspbc = json['dpcatatanspbc']?.toString();
    dpcatatankasubdiva = json['dpcatatankasubdiva']?.toString();
    dpcatatankasubdivb = json['dpcatatankasubdivb']?.toString();
    komphabispakai = json['komphabispakai']?.toString();
    komppengadaan = json['komppengadaan']?.toString();
    komphonor = json['komphonor']?.toString();
    komplainlain = json['komplainlain']?.toString();
    waktupengambilandata = json['waktupengambilandata']?.toString();
    spkverify = json['spkverify']?.toString();
    tglspkverify = json['tglspkverify']?.toString();
    tipependanaan = json['tipependanaan']?.toString();
    idFundrequest = json['id_fundrequest']?.toString();
    perkuliahanbukanfullcoursework = json['perkuliahanbukanfullcoursework']?.toString();
    bukutabungan = json['bukutabungan']?.toString();
    tgldiprosesbank = json['tgldiprosesbank']?.toString();
    updatedby = json['updatedby']?.toString();
    dpcatatantolakawardee = json['dpcatatantolakawardee']?.toString();
    matauangbank = json['matauangbank']?.toString();
    statuspayment = json['statuspayment']?.toString();
    nominativeiderpdelete = json['nominativeiderpdelete']?.toString();
    fundRequestCostItem = json['fund_request_cost_item']?.toString();
    fundRequestStatus = json['fund_request_status']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['koderegistrasi'] = koderegistrasi;
    data['costitem'] = costitem;
    data['currency'] = currency;
    data['requestamount'] = requestamount;
    data['requestamountidr'] = requestamountidr;
    data['bankaccount'] = bankaccount;
    data['jenispendanaanbank'] = jenispendanaanbank;
    data['paymentdesc'] = paymentdesc;
    data['remarks'] = remarks;
    data['lampiran'] = lampiran;
    data['tglpengajuan'] = tglpengajuan;
    data['iscard'] = iscard;
    data['tglupdate'] = tglupdate;
    data['approvedamount'] = approvedamount;
    data['approvedamountidr'] = approvedamountidr;
    data['catatan'] = catatan;
    data['uraianpembayaran'] = uraianpembayaran;
    data['remarksverify'] = remarksverify;
    data['awalperiode'] = awalperiode;
    data['akhirperiode'] = akhirperiode;
    data['status'] = status;
    data['userverify'] = userverify;
    data['dateverify'] = dateverify;
    data['nospp'] = nospp;
    data['nominativeid'] = nominativeid;
    data['dkuverify'] = dkuverify;
    data['tgldkuverify'] = tgldkuverify;
    data['statusdkuverify'] = statusdkuverify;
    data['catatandku'] = catatandku;
    data['tl'] = tl;
    data['tgltl'] = tgltl;
    data['catatanspb'] = catatanspb;
    data['kasubdivverify'] = kasubdivverify;
    data['tglkasubdivverify'] = tglkasubdivverify;
    data['statuskasubdivverify'] = statuskasubdivverify;
    data['catatankasubdiv'] = catatankasubdiv;
    data['catatanspbkasubdiv'] = catatanspbkasubdiv;
    data['tanggallapordirikjri'] = tanggallapordirikjri;
    data['nomorkkkel1'] = nomorkkkel1;
    data['nomorkkkel2'] = nomorkkkel2;
    data['nikkel1'] = nikkel1;
    data['nikkel2'] = nikkel2;
    data['namakel1'] = namakel1;
    data['namakel2'] = namakel2;
    data['tgllahirkel1'] = tgllahirkel1;
    data['tgllahirkel2'] = tgllahirkel2;
    data['tglkedatangan'] = tglkedatangan;
    data['bulanpengajuan'] = bulanpengajuan;
    data['tglkeberangkatan'] = tglkeberangkatan;
    data['bandaraasal'] = bandaraasal;
    data['bandaratujuan'] = bandaratujuan;
    data['pathtiket'] = pathtiket;
    data['kirimtagihan'] = kirimtagihan;
    data['nomorvisa'] = nomorvisa;
    data['nomorpaspor'] = nomorpaspor;
    data['durasitinggalstart'] = durasitinggalstart;
    data['durasitinggalend'] = durasitinggalend;
    data['createdbyrole'] = createdbyrole;
    data['kurs'] = kurs;
    data['isnp'] = isnp;
    data['namabank'] = namabank;
    data['alamatbank'] = alamatbank;
    data['atasnama'] = atasnama;
    data['nomorrekening'] = nomorrekening;
    data['swiftcode'] = swiftcode;
    data['iban'] = iban;
    data['billingidspp'] = billingidspp;
    data['judultesisdisertasi'] = judultesisdisertasi;
    data['labnonlab'] = labnonlab;
    data['namadosenpembimbing'] = namadosenpembimbing;
    data['emaildosenpembimbing'] = emaildosenpembimbing;
    data['tanggallulussempro'] = tanggallulussempro;
    data['tempatpengambilandata'] = tempatpengambilandata;
    data['fullcoursework'] = fullcoursework;
    data['skemapencairandana'] = skemapencairandana;
    data['sptjm'] = sptjm;
    data['beritaacarasidangseminar'] = beritaacarasidangseminar;
    data['lembarpengesahanproposaltesisdisertasi'] = lembarpengesahanproposaltesisdisertasi;
    data['penetapanpenelitian'] = penetapanpenelitian;
    data['suratketeranganbukanfullcoursework'] = suratketeranganbukanfullcoursework;
    data['proposaltesisdisertasi'] = proposaltesisdisertasi;
    data['pernyataandospemrabdisetujui'] = pernyataandospemrabdisetujui;
    data['suratketerangantidakdidanaiuniv'] = suratketerangantidakdidanaiuniv;
    data['pernyataantanggungjawabbelanja'] = pernyataantanggungjawabbelanja;
    data['rabaccdospem'] = rabaccdospem;
    data['dpcatatanspba'] = dpcatatanspba;
    data['dpcatatanspbb'] = dpcatatanspbb;
    data['dpcatatanspbc'] = dpcatatanspbc;
    data['dpcatatankasubdiva'] = dpcatatankasubdiva;
    data['dpcatatankasubdivb'] = dpcatatankasubdivb;
    data['komphabispakai'] = komphabispakai;
    data['komppengadaan'] = komppengadaan;
    data['komphonor'] = komphonor;
    data['komplainlain'] = komplainlain;
    data['waktupengambilandata'] = waktupengambilandata;
    data['spkverify'] = spkverify;
    data['tglspkverify'] = tglspkverify;
    data['tipependanaan'] = tipependanaan;
    data['id_fundrequest'] = idFundrequest;
    data['perkuliahanbukanfullcoursework'] = perkuliahanbukanfullcoursework;
    data['bukutabungan'] = bukutabungan;
    data['tgldiprosesbank'] = tgldiprosesbank;
    data['updatedby'] = updatedby;
    data['dpcatatantolakawardee'] = dpcatatantolakawardee;
    data['matauangbank'] = matauangbank;
    data['statuspayment'] = statuspayment;
    data['nominativeiderpdelete'] = nominativeiderpdelete;
    data['fund_request_cost_item'] = fundRequestCostItem;
    data['fund_request_status'] = fundRequestStatus;
    return data;
  }
}
