///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class Loslog {
/*
{
  "id": 12,
  "koderegistrasi": "0002356/BB/D/2/lpdp2016",
  "reqtype": 0,
  "status": 2,
  "userid": "",
  "tglpengajuan": "2020-07-22 09:40:21",
  "issipendob": 1,
  "idpengajuan": "LOG1268202072225022",
  "tipepengajuan": 3,
  "dnln": 1,
  "keperluan": null,
  "referensilos": null,
  "namakedutaan": null,
  "alamatkedutaan": "",
  "negara": "Indonesia",
  "universitas": "Universitas Indonesia",
  "univlainnya": null,
  "alamatuniv": "Kampus UI Depok Jawa Barat",
  "prodi": "Ilmu Linguistik",
  "lamastudi": 6,
  "mulaistudi": "28/08/2020",
  "tuitionfee": null,
  "isperpindahan": 0,
  "isfamily": 0,
  "allowance": 221,
  "allowanceother": null,
  "familyallowance": null,
  "isfamilyallowance": "0",
  "catatan": null,
  "tglupdate": "2020-07-22 09:40:21",
  "currencyid": 70,
  "rekomendasipic": "Setuju",
  "catatancpb_pb": null,
  "alasanrevisi": null,
  "programlog": null,
  "logrevisi": "Covid",
  "id_documentrequest": "2*yPN4}^9}",
  "akhirstudi": "Feb 26 2021 12:00:00:AM",
  "counterdok": 12,
  "nodokumen": "LOS-12/LPDP.3/2023",
  "tglpenerbitandok": "2023-11-01 18:09:28",
  "document": null,
  "issigning": null,
  "logsigning": null,
  "ipsigning": null,
  "browsersigning": null,
  "signeddate": null,
  "signedid": null,
  "komponenprogramjenjangid": 75,
  "idbookallowance": 62,
  "idsk": null,
  "isactive": 1,
  "namaperubahan": null,
  "islosnew": null,
  "islosseleksi": null,
  "keterangan": "",
  "code": "LOG",
  "kode_registrasi": "0002356/BB/D/2/lpdp2016",
  "nik": "1871092803790006",
  "batch_seleksi": "Tahun 2016 (Tahap 1)",
  "tahun_lolos_seleksi": 2016,
  "no_sk_seleksi": "KEP-16/LPDP/2016",
  "tanggal_sk_seleksi": "2016-03-10 00:00:00",
  "kategori_pembayaran": "Full Scholarship",
  "jenis_beasiswa": "Umum",
  "program_beasiswa": "Beasiswa Reguler",
  "jenis_cofunding": null,
  "jenjang_studi": "Doktor",
  "tujuan_beasiswa": "Dalam Negeri",
  "nama_lengkap": "MUKHAMMAD ISNAENI",
  "tempat_lahir": "PENGALEMAN",
  "tanggal_lahir": "Mar 28 1979 12:00:00:AM",
  "jenis_kelamin": "Laki-Laki",
  "email": "isnaeni.mhd@gmail.com",
  "kabkota": "KOTA BANDAR LAMPUNG",
  "provinsi": "LAMPUNG",
  "jenis_pekerjaan": "PNS Kementerian Pendidikan dan Kebudayaan",
  "instansi_kementerian_lembaga": "Kementerian Pendidikan, Kebudayaan, Riset, dan Teknologi",
  "bidang_karir": "Publik/PNS/Pegawai Profesional Kementerian",
  "sektor_karir": "Sektor Publik",
  "bidang_keilmuan": "Budaya, Seni dan Bahasa ",
  "prodi_asal": "Ilmu Pendidikan",
  "universitas_asal": "University of Twente",
  "prodi_tujuan_pendaftaran": "Ilmu Sastra",
  "universitas_tujuan_pendaftaran": "Universitas Indonesia",
  "negara_tujuan_pendaftaran": "Indonesia",
  "status_kontrak": "Sudah Kontrak",
  "tahun_kontrak": 2016,
  "no_induk_lpdp": "20160721118362",
  "batch_pk": "69",
  "jenjang_studi_kontrak": "Doktor",
  "tujuan_beasiswa_kontrak": "Dalam Negeri",
  "universitas_tujuan_kontrak": "Universitas Indonesia",
  "prodi_tujuan_kontrak": "Ilmu Linguistik",
  "benua_tujuan_kontrak": "Dalam Negeri",
  "negara_tujuan_kontrak": "Indonesia",
  "kota_tujuan_kontrak": "Jakarta",
  "bidang_keilmuan_kontrak": "Budaya, Seni dan Bahasa ",
  "awal_studi": "Aug 29 2016 12:00:00:AM",
  "akhir_studi": "Aug 28 2020 12:00:00:AM",
  "status_akademik": "On Going",
  "no_sk_penerima_beasiswa": null,
  "tanggal_penerbitan_sp": null,
  "jenis_pengajuan": null,
  "awal_studi_disetujui": "Aug 29 2016 12:00:00:AM",
  "akhir_studi_disetujui": "Feb 24 2021 12:00:00:AM",
  "no_surat_crm": null,
  "updated_date": "2020-03-23 19:29:19",
  "modified_by_id": 11,
  "alamat": "Jalan Diponegoro Gang Batugajah No.60 RT 008 LK.I Kelurahan Kupangteba, Telukbetung",
  "nama_bapak": "Muslimin",
  "nama_ibu": "Jumanah",
  "nama_pasangan": null,
  "status_menikah": null,
  "is_sp_dikembalikan": 0,
  "kabkota_saat_ini": null,
  "alamat_saat_ini": null,
  "komponen_biaya_cofunding": null,
  "is_dibuatkan_akun_simonev": 1,
  "negara_tujuan_kontrak_iso_code": "ID",
  "provinsi_asal_iso_code": "indonesia-lampung",
  "id_universitas_tujuan_kontrak": 245,
  "id_status_akademik": 5,
  "id_status_kontrak": 38,
  "id_program_beasiswa": 12,
  "id_jenjang_studi": 2,
  "id_tujuan_beasiswa": 1,
  "id_kabkota_asal": 609,
  "no_induk_mahasiswa": "1606848351",
  "durasi_studi": 54,
  "frekuensi_dana_hidup": 16,
  "bahasa_skor_pendaftaran": "6",
  "bahasa_jenis_tes_pendaftaran": "Inggris (IELTS)",
  "email_saat_ini": null,
  "no_hp_saat_ini": "082280373803",
  "awal_studi_2": "Aug 29 2016 12:00:00:AM",
  "akhir_studi_2": "Feb 24 2021 12:00:00:AM",
  "awal_studi_3": "Aug 29 2016 12:00:00:AM",
  "akhir_studi_3": "Feb 24 2021 12:00:00:AM",
  "awal_studi_4": null,
  "akhir_studi_4": null,
  "sumber_info_durasi_studi": null,
  "catatan_kontrak": "Mengajukan perubahan durasi studi ke Subdivisi Monitoring dan Evaluasi Beasiswa dan telah mendapatkan persetujuan Direktur Beasiswa",
  "link_foto": "http://beasiswa.lpdp.depkeu.go.id/foto/2016/01/14/152589-Mukhammad Isnaeni/618542_potoku 2.jpg",
  "tanggal_sk_penerima_beasiswa": null,
  "nama_lengkap_lama": null,
  "id_universitas_tujuan_kontrak_lama": null,
  "prodi_tujuan_kontrak_lama": null,
  "id_tujuan_beasiswa_lama": null,
  "tanggal_sk_penerima_beasiswa_revisi": null,
  "no_sk_penerima_beasiswa_revisi": null,
  "no_sk_penerima_beasiswa_sebelumnya": null,
  "catatan_seleksi": null,
  "nidn": null,
  "nuptk": null,
  "id_sekolah": null,
  "tanggal_sk_berlaku_sejak": null,
  "id_provinsi_saat_ini": null,
  "id_status_beasiswa": 33,
  "id_status_akademik_universitas": 39,
  "id_status_pembiayaan": 36,
  "tanggal_deadline_pencarian_loa": null,
  "id_kelas": 1,
  "awardee_fakultas": "Ilmu Pengetahuan Budaya",
  "awardee_nama_pa": null,
  "awardee_telephone_pa": null,
  "awardee_email_pa": null,
  "awardee_nama_promotor": null,
  "awardee_telephone_promotor": null,
  "awardee_email_promotor": null,
  "awardee_tanggal_masuk": "Jul 28 2016 12:00:00:AM",
  "awardee_batas_studi": "8",
  "awardee_tanggal_lulus": null,
  "awardee_tanggal_yudisium": null,
  "awardee_nomor_ijazah": null,
  "perkembangan_ipk": "0",
  "awardee_jurusan_universitas": "Ilmu Linguistik",
  "pns_unit_eselon_1": null,
  "pns_unit_eselon_2": null,
  "id_fakultas": null,
  "id_program_studi": null,
  "hak_spp": 9,
  "ishaveloafromseleksi": null,
  "is_active": 1,
  "template_sp": "sp_general",
  "template_sk": null,
  "nextstatus": 3,
  "role": "Kadiv-Alumni",
  "idmodule": 13
} 
*/

  int? id;
  String? koderegistrasi;
  int? reqtype;
  int? status;
  String? userid;
  String? tglpengajuan;
  int? issipendob;
  String? idpengajuan;
  int? tipepengajuan;
  int? dnln;
  String? keperluan;
  String? referensilos;
  String? namakedutaan;
  String? alamatkedutaan;
  String? negara;
  String? universitas;
  String? univlainnya;
  String? alamatuniv;
  String? prodi;
  int? lamastudi;
  String? mulaistudi;
  String? tuitionfee;
  int? isperpindahan;
  int? isfamily;
  int? allowance;
  String? allowanceother;
  String? familyallowance;
  String? isfamilyallowance;
  String? catatan;
  String? tglupdate;
  int? currencyid;
  String? rekomendasipic;
  String? catatancpbPb;
  String? alasanrevisi;
  String? programlog;
  String? logrevisi;
  String? idDocumentrequest;
  String? akhirstudi;
  int? counterdok;
  String? nodokumen;
  String? tglpenerbitandok;
  String? document;
  String? issigning;
  String? logsigning;
  String? ipsigning;
  String? browsersigning;
  String? signeddate;
  String? signedid;
  int? komponenprogramjenjangid;
  int? idbookallowance;
  String? idsk;
  int? isactive;
  String? namaperubahan;
  String? islosnew;
  String? islosseleksi;
  String? keterangan;
  String? code;
  String? kodeRegistrasi;
  String? nik;
  String? batchSeleksi;
  int? tahunLolosSeleksi;
  String? noSkSeleksi;
  String? tanggalSkSeleksi;
  String? kategoriPembayaran;
  String? jenisBeasiswa;
  String? programBeasiswa;
  String? jenisCofunding;
  String? jenjangStudi;
  String? tujuanBeasiswa;
  String? namaLengkap;
  String? tempatLahir;
  String? tanggalLahir;
  String? jenisKelamin;
  String? email;
  String? kabkota;
  String? provinsi;
  String? jenisPekerjaan;
  String? instansiKementerianLembaga;
  String? bidangKarir;
  String? sektorKarir;
  String? bidangKeilmuan;
  String? prodiAsal;
  String? universitasAsal;
  String? prodiTujuanPendaftaran;
  String? universitasTujuanPendaftaran;
  String? negaraTujuanPendaftaran;
  String? statusKontrak;
  int? tahunKontrak;
  String? noIndukLpdp;
  String? batchPk;
  String? jenjangStudiKontrak;
  String? tujuanBeasiswaKontrak;
  String? universitasTujuanKontrak;
  String? prodiTujuanKontrak;
  String? benuaTujuanKontrak;
  String? negaraTujuanKontrak;
  String? kotaTujuanKontrak;
  String? bidangKeilmuanKontrak;
  String? awalStudi;
  String? akhirStudi;
  String? statusAkademik;
  String? noSkPenerimaBeasiswa;
  String? tanggalPenerbitanSp;
  String? jenisPengajuan;
  String? awalStudiDisetujui;
  String? akhirStudiDisetujui;
  String? noSuratCrm;
  String? updatedDate;
  int? modifiedById;
  String? alamat;
  String? namaBapak;
  String? namaIbu;
  String? namaPasangan;
  String? statusMenikah;
  int? isSpDikembalikan;
  String? kabkotaSaatIni;
  String? alamatSaatIni;
  String? komponenBiayaCofunding;
  int? isDibuatkanAkunSimonev;
  String? negaraTujuanKontrakIsoCode;
  String? provinsiAsalIsoCode;
  int? idUniversitasTujuanKontrak;
  int? idStatusAkademik;
  int? idStatusKontrak;
  int? idProgramBeasiswa;
  int? idJenjangStudi;
  int? idTujuanBeasiswa;
  int? idKabkotaAsal;
  String? noIndukMahasiswa;
  int? durasiStudi;
  int? frekuensiDanaHidup;
  String? bahasaSkorPendaftaran;
  String? bahasaJenisTesPendaftaran;
  String? emailSaatIni;
  String? noHpSaatIni;
  String? awalStudi_2;
  String? akhirStudi_2;
  String? awalStudi_3;
  String? akhirStudi_3;
  String? awalStudi_4;
  String? akhirStudi_4;
  String? sumberInfoDurasiStudi;
  String? catatanKontrak;
  String? linkFoto;
  String? tanggalSkPenerimaBeasiswa;
  String? namaLengkapLama;
  String? idUniversitasTujuanKontrakLama;
  String? prodiTujuanKontrakLama;
  String? idTujuanBeasiswaLama;
  String? tanggalSkPenerimaBeasiswaRevisi;
  String? noSkPenerimaBeasiswaRevisi;
  String? noSkPenerimaBeasiswaSebelumnya;
  String? catatanSeleksi;
  String? nidn;
  String? nuptk;
  String? idSekolah;
  String? tanggalSkBerlakuSejak;
  String? idProvinsiSaatIni;
  int? idStatusBeasiswa;
  int? idStatusAkademikUniversitas;
  int? idStatusPembiayaan;
  String? tanggalDeadlinePencarianLoa;
  int? idKelas;
  String? awardeeFakultas;
  String? awardeeNamaPa;
  String? awardeeTelephonePa;
  String? awardeeEmailPa;
  String? awardeeNamaPromotor;
  String? awardeeTelephonePromotor;
  String? awardeeEmailPromotor;
  String? awardeeTanggalMasuk;
  String? awardeeBatasStudi;
  String? awardeeTanggalLulus;
  String? awardeeTanggalYudisium;
  String? awardeeNomorIjazah;
  String? perkembanganIpk;
  String? awardeeJurusanUniversitas;
  String? pnsUnitEselon_1;
  String? pnsUnitEselon_2;
  String? idFakultas;
  String? idProgramStudi;
  int? hakSpp;
  String? ishaveloafromseleksi;
  int? isActive;
  String? templateSp;
  String? templateSk;
  int? nextstatus;
  String? role;
  int? idmodule;

  Loslog({
    this.id,
    this.koderegistrasi,
    this.reqtype,
    this.status,
    this.userid,
    this.tglpengajuan,
    this.issipendob,
    this.idpengajuan,
    this.tipepengajuan,
    this.dnln,
    this.keperluan,
    this.referensilos,
    this.namakedutaan,
    this.alamatkedutaan,
    this.negara,
    this.universitas,
    this.univlainnya,
    this.alamatuniv,
    this.prodi,
    this.lamastudi,
    this.mulaistudi,
    this.tuitionfee,
    this.isperpindahan,
    this.isfamily,
    this.allowance,
    this.allowanceother,
    this.familyallowance,
    this.isfamilyallowance,
    this.catatan,
    this.tglupdate,
    this.currencyid,
    this.rekomendasipic,
    this.catatancpbPb,
    this.alasanrevisi,
    this.programlog,
    this.logrevisi,
    this.idDocumentrequest,
    this.akhirstudi,
    this.counterdok,
    this.nodokumen,
    this.tglpenerbitandok,
    this.document,
    this.issigning,
    this.logsigning,
    this.ipsigning,
    this.browsersigning,
    this.signeddate,
    this.signedid,
    this.komponenprogramjenjangid,
    this.idbookallowance,
    this.idsk,
    this.isactive,
    this.namaperubahan,
    this.islosnew,
    this.islosseleksi,
    this.keterangan,
    this.code,
    this.kodeRegistrasi,
    this.nik,
    this.batchSeleksi,
    this.tahunLolosSeleksi,
    this.noSkSeleksi,
    this.tanggalSkSeleksi,
    this.kategoriPembayaran,
    this.jenisBeasiswa,
    this.programBeasiswa,
    this.jenisCofunding,
    this.jenjangStudi,
    this.tujuanBeasiswa,
    this.namaLengkap,
    this.tempatLahir,
    this.tanggalLahir,
    this.jenisKelamin,
    this.email,
    this.kabkota,
    this.provinsi,
    this.jenisPekerjaan,
    this.instansiKementerianLembaga,
    this.bidangKarir,
    this.sektorKarir,
    this.bidangKeilmuan,
    this.prodiAsal,
    this.universitasAsal,
    this.prodiTujuanPendaftaran,
    this.universitasTujuanPendaftaran,
    this.negaraTujuanPendaftaran,
    this.statusKontrak,
    this.tahunKontrak,
    this.noIndukLpdp,
    this.batchPk,
    this.jenjangStudiKontrak,
    this.tujuanBeasiswaKontrak,
    this.universitasTujuanKontrak,
    this.prodiTujuanKontrak,
    this.benuaTujuanKontrak,
    this.negaraTujuanKontrak,
    this.kotaTujuanKontrak,
    this.bidangKeilmuanKontrak,
    this.awalStudi,
    this.akhirStudi,
    this.statusAkademik,
    this.noSkPenerimaBeasiswa,
    this.tanggalPenerbitanSp,
    this.jenisPengajuan,
    this.awalStudiDisetujui,
    this.akhirStudiDisetujui,
    this.noSuratCrm,
    this.updatedDate,
    this.modifiedById,
    this.alamat,
    this.namaBapak,
    this.namaIbu,
    this.namaPasangan,
    this.statusMenikah,
    this.isSpDikembalikan,
    this.kabkotaSaatIni,
    this.alamatSaatIni,
    this.komponenBiayaCofunding,
    this.isDibuatkanAkunSimonev,
    this.negaraTujuanKontrakIsoCode,
    this.provinsiAsalIsoCode,
    this.idUniversitasTujuanKontrak,
    this.idStatusAkademik,
    this.idStatusKontrak,
    this.idProgramBeasiswa,
    this.idJenjangStudi,
    this.idTujuanBeasiswa,
    this.idKabkotaAsal,
    this.noIndukMahasiswa,
    this.durasiStudi,
    this.frekuensiDanaHidup,
    this.bahasaSkorPendaftaran,
    this.bahasaJenisTesPendaftaran,
    this.emailSaatIni,
    this.noHpSaatIni,
    this.awalStudi_2,
    this.akhirStudi_2,
    this.awalStudi_3,
    this.akhirStudi_3,
    this.awalStudi_4,
    this.akhirStudi_4,
    this.sumberInfoDurasiStudi,
    this.catatanKontrak,
    this.linkFoto,
    this.tanggalSkPenerimaBeasiswa,
    this.namaLengkapLama,
    this.idUniversitasTujuanKontrakLama,
    this.prodiTujuanKontrakLama,
    this.idTujuanBeasiswaLama,
    this.tanggalSkPenerimaBeasiswaRevisi,
    this.noSkPenerimaBeasiswaRevisi,
    this.noSkPenerimaBeasiswaSebelumnya,
    this.catatanSeleksi,
    this.nidn,
    this.nuptk,
    this.idSekolah,
    this.tanggalSkBerlakuSejak,
    this.idProvinsiSaatIni,
    this.idStatusBeasiswa,
    this.idStatusAkademikUniversitas,
    this.idStatusPembiayaan,
    this.tanggalDeadlinePencarianLoa,
    this.idKelas,
    this.awardeeFakultas,
    this.awardeeNamaPa,
    this.awardeeTelephonePa,
    this.awardeeEmailPa,
    this.awardeeNamaPromotor,
    this.awardeeTelephonePromotor,
    this.awardeeEmailPromotor,
    this.awardeeTanggalMasuk,
    this.awardeeBatasStudi,
    this.awardeeTanggalLulus,
    this.awardeeTanggalYudisium,
    this.awardeeNomorIjazah,
    this.perkembanganIpk,
    this.awardeeJurusanUniversitas,
    this.pnsUnitEselon_1,
    this.pnsUnitEselon_2,
    this.idFakultas,
    this.idProgramStudi,
    this.hakSpp,
    this.ishaveloafromseleksi,
    this.isActive,
    this.templateSp,
    this.templateSk,
    this.nextstatus,
    this.role,
    this.idmodule,
  });
  Loslog.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    koderegistrasi = json['koderegistrasi']?.toString();
    reqtype = json['reqtype']?.toInt();
    status = json['status']?.toInt();
    userid = json['userid']?.toString();
    tglpengajuan = json['tglpengajuan']?.toString();
    issipendob = json['issipendob']?.toInt();
    idpengajuan = json['idpengajuan']?.toString();
    tipepengajuan = json['tipepengajuan']?.toInt();
    dnln = json['dnln']?.toInt();
    keperluan = json['keperluan']?.toString();
    referensilos = json['referensilos']?.toString();
    namakedutaan = json['namakedutaan']?.toString();
    alamatkedutaan = json['alamatkedutaan']?.toString();
    negara = json['negara']?.toString();
    universitas = json['universitas']?.toString();
    univlainnya = json['univlainnya']?.toString();
    alamatuniv = json['alamatuniv']?.toString();
    prodi = json['prodi']?.toString();
    lamastudi = json['lamastudi']?.toInt();
    mulaistudi = json['mulaistudi']?.toString();
    tuitionfee = json['tuitionfee']?.toString();
    isperpindahan = json['isperpindahan']?.toInt();
    isfamily = json['isfamily']?.toInt();
    allowance = json['allowance']?.toInt();
    allowanceother = json['allowanceother']?.toString();
    familyallowance = json['familyallowance']?.toString();
    isfamilyallowance = json['isfamilyallowance']?.toString();
    catatan = json['catatan']?.toString();
    tglupdate = json['tglupdate']?.toString();
    currencyid = json['currencyid']?.toInt();
    rekomendasipic = json['rekomendasipic']?.toString();
    catatancpbPb = json['catatancpb_pb']?.toString();
    alasanrevisi = json['alasanrevisi']?.toString();
    programlog = json['programlog']?.toString();
    logrevisi = json['logrevisi']?.toString();
    idDocumentrequest = json['id_documentrequest']?.toString();
    akhirstudi = json['akhirstudi']?.toString();
    counterdok = json['counterdok']?.toInt();
    nodokumen = json['nodokumen']?.toString();
    tglpenerbitandok = json['tglpenerbitandok']?.toString();
    document = json['document']?.toString();
    issigning = json['issigning']?.toString();
    logsigning = json['logsigning']?.toString();
    ipsigning = json['ipsigning']?.toString();
    browsersigning = json['browsersigning']?.toString();
    signeddate = json['signeddate']?.toString();
    signedid = json['signedid']?.toString();
    komponenprogramjenjangid = json['komponenprogramjenjangid']?.toInt();
    idbookallowance = json['idbookallowance']?.toInt();
    idsk = json['idsk']?.toString();
    isactive = json['isactive']?.toInt();
    namaperubahan = json['namaperubahan']?.toString();
    islosnew = json['islosnew']?.toString();
    islosseleksi = json['islosseleksi']?.toString();
    keterangan = json['keterangan']?.toString();
    code = json['code']?.toString();
    kodeRegistrasi = json['kode_registrasi']?.toString();
    nik = json['nik']?.toString();
    batchSeleksi = json['batch_seleksi']?.toString();
    tahunLolosSeleksi = json['tahun_lolos_seleksi']?.toInt();
    noSkSeleksi = json['no_sk_seleksi']?.toString();
    tanggalSkSeleksi = json['tanggal_sk_seleksi']?.toString();
    kategoriPembayaran = json['kategori_pembayaran']?.toString();
    jenisBeasiswa = json['jenis_beasiswa']?.toString();
    programBeasiswa = json['program_beasiswa']?.toString();
    jenisCofunding = json['jenis_cofunding']?.toString();
    jenjangStudi = json['jenjang_studi']?.toString();
    tujuanBeasiswa = json['tujuan_beasiswa']?.toString();
    namaLengkap = json['nama_lengkap']?.toString();
    tempatLahir = json['tempat_lahir']?.toString();
    tanggalLahir = json['tanggal_lahir']?.toString();
    jenisKelamin = json['jenis_kelamin']?.toString();
    email = json['email']?.toString();
    kabkota = json['kabkota']?.toString();
    provinsi = json['provinsi']?.toString();
    jenisPekerjaan = json['jenis_pekerjaan']?.toString();
    instansiKementerianLembaga = json['instansi_kementerian_lembaga']?.toString();
    bidangKarir = json['bidang_karir']?.toString();
    sektorKarir = json['sektor_karir']?.toString();
    bidangKeilmuan = json['bidang_keilmuan']?.toString();
    prodiAsal = json['prodi_asal']?.toString();
    universitasAsal = json['universitas_asal']?.toString();
    prodiTujuanPendaftaran = json['prodi_tujuan_pendaftaran']?.toString();
    universitasTujuanPendaftaran = json['universitas_tujuan_pendaftaran']?.toString();
    negaraTujuanPendaftaran = json['negara_tujuan_pendaftaran']?.toString();
    statusKontrak = json['status_kontrak']?.toString();
    tahunKontrak = json['tahun_kontrak']?.toInt();
    noIndukLpdp = json['no_induk_lpdp']?.toString();
    batchPk = json['batch_pk']?.toString();
    jenjangStudiKontrak = json['jenjang_studi_kontrak']?.toString();
    tujuanBeasiswaKontrak = json['tujuan_beasiswa_kontrak']?.toString();
    universitasTujuanKontrak = json['universitas_tujuan_kontrak']?.toString();
    prodiTujuanKontrak = json['prodi_tujuan_kontrak']?.toString();
    benuaTujuanKontrak = json['benua_tujuan_kontrak']?.toString();
    negaraTujuanKontrak = json['negara_tujuan_kontrak']?.toString();
    kotaTujuanKontrak = json['kota_tujuan_kontrak']?.toString();
    bidangKeilmuanKontrak = json['bidang_keilmuan_kontrak']?.toString();
    awalStudi = json['awal_studi']?.toString();
    akhirStudi = json['akhir_studi']?.toString();
    statusAkademik = json['status_akademik']?.toString();
    noSkPenerimaBeasiswa = json['no_sk_penerima_beasiswa']?.toString();
    tanggalPenerbitanSp = json['tanggal_penerbitan_sp']?.toString();
    jenisPengajuan = json['jenis_pengajuan']?.toString();
    awalStudiDisetujui = json['awal_studi_disetujui']?.toString();
    akhirStudiDisetujui = json['akhir_studi_disetujui']?.toString();
    noSuratCrm = json['no_surat_crm']?.toString();
    updatedDate = json['updated_date']?.toString();
    modifiedById = json['modified_by_id']?.toInt();
    alamat = json['alamat']?.toString();
    namaBapak = json['nama_bapak']?.toString();
    namaIbu = json['nama_ibu']?.toString();
    namaPasangan = json['nama_pasangan']?.toString();
    statusMenikah = json['status_menikah']?.toString();
    isSpDikembalikan = json['is_sp_dikembalikan']?.toInt();
    kabkotaSaatIni = json['kabkota_saat_ini']?.toString();
    alamatSaatIni = json['alamat_saat_ini']?.toString();
    komponenBiayaCofunding = json['komponen_biaya_cofunding']?.toString();
    isDibuatkanAkunSimonev = json['is_dibuatkan_akun_simonev']?.toInt();
    negaraTujuanKontrakIsoCode = json['negara_tujuan_kontrak_iso_code']?.toString();
    provinsiAsalIsoCode = json['provinsi_asal_iso_code']?.toString();
    idUniversitasTujuanKontrak = json['id_universitas_tujuan_kontrak']?.toInt();
    idStatusAkademik = json['id_status_akademik']?.toInt();
    idStatusKontrak = json['id_status_kontrak']?.toInt();
    idProgramBeasiswa = json['id_program_beasiswa']?.toInt();
    idJenjangStudi = json['id_jenjang_studi']?.toInt();
    idTujuanBeasiswa = json['id_tujuan_beasiswa']?.toInt();
    idKabkotaAsal = json['id_kabkota_asal']?.toInt();
    noIndukMahasiswa = json['no_induk_mahasiswa']?.toString();
    durasiStudi = json['durasi_studi']?.toInt();
    frekuensiDanaHidup = json['frekuensi_dana_hidup']?.toInt();
    bahasaSkorPendaftaran = json['bahasa_skor_pendaftaran']?.toString();
    bahasaJenisTesPendaftaran = json['bahasa_jenis_tes_pendaftaran']?.toString();
    emailSaatIni = json['email_saat_ini']?.toString();
    noHpSaatIni = json['no_hp_saat_ini']?.toString();
    awalStudi_2 = json['awal_studi_2']?.toString();
    akhirStudi_2 = json['akhir_studi_2']?.toString();
    awalStudi_3 = json['awal_studi_3']?.toString();
    akhirStudi_3 = json['akhir_studi_3']?.toString();
    awalStudi_4 = json['awal_studi_4']?.toString();
    akhirStudi_4 = json['akhir_studi_4']?.toString();
    sumberInfoDurasiStudi = json['sumber_info_durasi_studi']?.toString();
    catatanKontrak = json['catatan_kontrak']?.toString();
    linkFoto = json['link_foto']?.toString();
    tanggalSkPenerimaBeasiswa = json['tanggal_sk_penerima_beasiswa']?.toString();
    namaLengkapLama = json['nama_lengkap_lama']?.toString();
    idUniversitasTujuanKontrakLama = json['id_universitas_tujuan_kontrak_lama']?.toString();
    prodiTujuanKontrakLama = json['prodi_tujuan_kontrak_lama']?.toString();
    idTujuanBeasiswaLama = json['id_tujuan_beasiswa_lama']?.toString();
    tanggalSkPenerimaBeasiswaRevisi = json['tanggal_sk_penerima_beasiswa_revisi']?.toString();
    noSkPenerimaBeasiswaRevisi = json['no_sk_penerima_beasiswa_revisi']?.toString();
    noSkPenerimaBeasiswaSebelumnya = json['no_sk_penerima_beasiswa_sebelumnya']?.toString();
    catatanSeleksi = json['catatan_seleksi']?.toString();
    nidn = json['nidn']?.toString();
    nuptk = json['nuptk']?.toString();
    idSekolah = json['id_sekolah']?.toString();
    tanggalSkBerlakuSejak = json['tanggal_sk_berlaku_sejak']?.toString();
    idProvinsiSaatIni = json['id_provinsi_saat_ini']?.toString();
    idStatusBeasiswa = json['id_status_beasiswa']?.toInt();
    idStatusAkademikUniversitas = json['id_status_akademik_universitas']?.toInt();
    idStatusPembiayaan = json['id_status_pembiayaan']?.toInt();
    tanggalDeadlinePencarianLoa = json['tanggal_deadline_pencarian_loa']?.toString();
    idKelas = json['id_kelas']?.toInt();
    awardeeFakultas = json['awardee_fakultas']?.toString();
    awardeeNamaPa = json['awardee_nama_pa']?.toString();
    awardeeTelephonePa = json['awardee_telephone_pa']?.toString();
    awardeeEmailPa = json['awardee_email_pa']?.toString();
    awardeeNamaPromotor = json['awardee_nama_promotor']?.toString();
    awardeeTelephonePromotor = json['awardee_telephone_promotor']?.toString();
    awardeeEmailPromotor = json['awardee_email_promotor']?.toString();
    awardeeTanggalMasuk = json['awardee_tanggal_masuk']?.toString();
    awardeeBatasStudi = json['awardee_batas_studi']?.toString();
    awardeeTanggalLulus = json['awardee_tanggal_lulus']?.toString();
    awardeeTanggalYudisium = json['awardee_tanggal_yudisium']?.toString();
    awardeeNomorIjazah = json['awardee_nomor_ijazah']?.toString();
    perkembanganIpk = json['perkembangan_ipk']?.toString();
    awardeeJurusanUniversitas = json['awardee_jurusan_universitas']?.toString();
    pnsUnitEselon_1 = json['pns_unit_eselon_1']?.toString();
    pnsUnitEselon_2 = json['pns_unit_eselon_2']?.toString();
    idFakultas = json['id_fakultas']?.toString();
    idProgramStudi = json['id_program_studi']?.toString();
    hakSpp = json['hak_spp']?.toInt();
    ishaveloafromseleksi = json['ishaveloafromseleksi']?.toString();
    isActive = json['is_active']?.toInt();
    templateSp = json['template_sp']?.toString();
    templateSk = json['template_sk']?.toString();
    nextstatus = json['nextstatus']?.toInt();
    role = json['role']?.toString();
    idmodule = json['idmodule']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['koderegistrasi'] = koderegistrasi;
    data['reqtype'] = reqtype;
    data['status'] = status;
    data['userid'] = userid;
    data['tglpengajuan'] = tglpengajuan;
    data['issipendob'] = issipendob;
    data['idpengajuan'] = idpengajuan;
    data['tipepengajuan'] = tipepengajuan;
    data['dnln'] = dnln;
    data['keperluan'] = keperluan;
    data['referensilos'] = referensilos;
    data['namakedutaan'] = namakedutaan;
    data['alamatkedutaan'] = alamatkedutaan;
    data['negara'] = negara;
    data['universitas'] = universitas;
    data['univlainnya'] = univlainnya;
    data['alamatuniv'] = alamatuniv;
    data['prodi'] = prodi;
    data['lamastudi'] = lamastudi;
    data['mulaistudi'] = mulaistudi;
    data['tuitionfee'] = tuitionfee;
    data['isperpindahan'] = isperpindahan;
    data['isfamily'] = isfamily;
    data['allowance'] = allowance;
    data['allowanceother'] = allowanceother;
    data['familyallowance'] = familyallowance;
    data['isfamilyallowance'] = isfamilyallowance;
    data['catatan'] = catatan;
    data['tglupdate'] = tglupdate;
    data['currencyid'] = currencyid;
    data['rekomendasipic'] = rekomendasipic;
    data['catatancpb_pb'] = catatancpbPb;
    data['alasanrevisi'] = alasanrevisi;
    data['programlog'] = programlog;
    data['logrevisi'] = logrevisi;
    data['id_documentrequest'] = idDocumentrequest;
    data['akhirstudi'] = akhirstudi;
    data['counterdok'] = counterdok;
    data['nodokumen'] = nodokumen;
    data['tglpenerbitandok'] = tglpenerbitandok;
    data['document'] = document;
    data['issigning'] = issigning;
    data['logsigning'] = logsigning;
    data['ipsigning'] = ipsigning;
    data['browsersigning'] = browsersigning;
    data['signeddate'] = signeddate;
    data['signedid'] = signedid;
    data['komponenprogramjenjangid'] = komponenprogramjenjangid;
    data['idbookallowance'] = idbookallowance;
    data['idsk'] = idsk;
    data['isactive'] = isactive;
    data['namaperubahan'] = namaperubahan;
    data['islosnew'] = islosnew;
    data['islosseleksi'] = islosseleksi;
    data['keterangan'] = keterangan;
    data['code'] = code;
    data['kode_registrasi'] = kodeRegistrasi;
    data['nik'] = nik;
    data['batch_seleksi'] = batchSeleksi;
    data['tahun_lolos_seleksi'] = tahunLolosSeleksi;
    data['no_sk_seleksi'] = noSkSeleksi;
    data['tanggal_sk_seleksi'] = tanggalSkSeleksi;
    data['kategori_pembayaran'] = kategoriPembayaran;
    data['jenis_beasiswa'] = jenisBeasiswa;
    data['program_beasiswa'] = programBeasiswa;
    data['jenis_cofunding'] = jenisCofunding;
    data['jenjang_studi'] = jenjangStudi;
    data['tujuan_beasiswa'] = tujuanBeasiswa;
    data['nama_lengkap'] = namaLengkap;
    data['tempat_lahir'] = tempatLahir;
    data['tanggal_lahir'] = tanggalLahir;
    data['jenis_kelamin'] = jenisKelamin;
    data['email'] = email;
    data['kabkota'] = kabkota;
    data['provinsi'] = provinsi;
    data['jenis_pekerjaan'] = jenisPekerjaan;
    data['instansi_kementerian_lembaga'] = instansiKementerianLembaga;
    data['bidang_karir'] = bidangKarir;
    data['sektor_karir'] = sektorKarir;
    data['bidang_keilmuan'] = bidangKeilmuan;
    data['prodi_asal'] = prodiAsal;
    data['universitas_asal'] = universitasAsal;
    data['prodi_tujuan_pendaftaran'] = prodiTujuanPendaftaran;
    data['universitas_tujuan_pendaftaran'] = universitasTujuanPendaftaran;
    data['negara_tujuan_pendaftaran'] = negaraTujuanPendaftaran;
    data['status_kontrak'] = statusKontrak;
    data['tahun_kontrak'] = tahunKontrak;
    data['no_induk_lpdp'] = noIndukLpdp;
    data['batch_pk'] = batchPk;
    data['jenjang_studi_kontrak'] = jenjangStudiKontrak;
    data['tujuan_beasiswa_kontrak'] = tujuanBeasiswaKontrak;
    data['universitas_tujuan_kontrak'] = universitasTujuanKontrak;
    data['prodi_tujuan_kontrak'] = prodiTujuanKontrak;
    data['benua_tujuan_kontrak'] = benuaTujuanKontrak;
    data['negara_tujuan_kontrak'] = negaraTujuanKontrak;
    data['kota_tujuan_kontrak'] = kotaTujuanKontrak;
    data['bidang_keilmuan_kontrak'] = bidangKeilmuanKontrak;
    data['awal_studi'] = awalStudi;
    data['akhir_studi'] = akhirStudi;
    data['status_akademik'] = statusAkademik;
    data['no_sk_penerima_beasiswa'] = noSkPenerimaBeasiswa;
    data['tanggal_penerbitan_sp'] = tanggalPenerbitanSp;
    data['jenis_pengajuan'] = jenisPengajuan;
    data['awal_studi_disetujui'] = awalStudiDisetujui;
    data['akhir_studi_disetujui'] = akhirStudiDisetujui;
    data['no_surat_crm'] = noSuratCrm;
    data['updated_date'] = updatedDate;
    data['modified_by_id'] = modifiedById;
    data['alamat'] = alamat;
    data['nama_bapak'] = namaBapak;
    data['nama_ibu'] = namaIbu;
    data['nama_pasangan'] = namaPasangan;
    data['status_menikah'] = statusMenikah;
    data['is_sp_dikembalikan'] = isSpDikembalikan;
    data['kabkota_saat_ini'] = kabkotaSaatIni;
    data['alamat_saat_ini'] = alamatSaatIni;
    data['komponen_biaya_cofunding'] = komponenBiayaCofunding;
    data['is_dibuatkan_akun_simonev'] = isDibuatkanAkunSimonev;
    data['negara_tujuan_kontrak_iso_code'] = negaraTujuanKontrakIsoCode;
    data['provinsi_asal_iso_code'] = provinsiAsalIsoCode;
    data['id_universitas_tujuan_kontrak'] = idUniversitasTujuanKontrak;
    data['id_status_akademik'] = idStatusAkademik;
    data['id_status_kontrak'] = idStatusKontrak;
    data['id_program_beasiswa'] = idProgramBeasiswa;
    data['id_jenjang_studi'] = idJenjangStudi;
    data['id_tujuan_beasiswa'] = idTujuanBeasiswa;
    data['id_kabkota_asal'] = idKabkotaAsal;
    data['no_induk_mahasiswa'] = noIndukMahasiswa;
    data['durasi_studi'] = durasiStudi;
    data['frekuensi_dana_hidup'] = frekuensiDanaHidup;
    data['bahasa_skor_pendaftaran'] = bahasaSkorPendaftaran;
    data['bahasa_jenis_tes_pendaftaran'] = bahasaJenisTesPendaftaran;
    data['email_saat_ini'] = emailSaatIni;
    data['no_hp_saat_ini'] = noHpSaatIni;
    data['awal_studi_2'] = awalStudi_2;
    data['akhir_studi_2'] = akhirStudi_2;
    data['awal_studi_3'] = awalStudi_3;
    data['akhir_studi_3'] = akhirStudi_3;
    data['awal_studi_4'] = awalStudi_4;
    data['akhir_studi_4'] = akhirStudi_4;
    data['sumber_info_durasi_studi'] = sumberInfoDurasiStudi;
    data['catatan_kontrak'] = catatanKontrak;
    data['link_foto'] = linkFoto;
    data['tanggal_sk_penerima_beasiswa'] = tanggalSkPenerimaBeasiswa;
    data['nama_lengkap_lama'] = namaLengkapLama;
    data['id_universitas_tujuan_kontrak_lama'] = idUniversitasTujuanKontrakLama;
    data['prodi_tujuan_kontrak_lama'] = prodiTujuanKontrakLama;
    data['id_tujuan_beasiswa_lama'] = idTujuanBeasiswaLama;
    data['tanggal_sk_penerima_beasiswa_revisi'] = tanggalSkPenerimaBeasiswaRevisi;
    data['no_sk_penerima_beasiswa_revisi'] = noSkPenerimaBeasiswaRevisi;
    data['no_sk_penerima_beasiswa_sebelumnya'] = noSkPenerimaBeasiswaSebelumnya;
    data['catatan_seleksi'] = catatanSeleksi;
    data['nidn'] = nidn;
    data['nuptk'] = nuptk;
    data['id_sekolah'] = idSekolah;
    data['tanggal_sk_berlaku_sejak'] = tanggalSkBerlakuSejak;
    data['id_provinsi_saat_ini'] = idProvinsiSaatIni;
    data['id_status_beasiswa'] = idStatusBeasiswa;
    data['id_status_akademik_universitas'] = idStatusAkademikUniversitas;
    data['id_status_pembiayaan'] = idStatusPembiayaan;
    data['tanggal_deadline_pencarian_loa'] = tanggalDeadlinePencarianLoa;
    data['id_kelas'] = idKelas;
    data['awardee_fakultas'] = awardeeFakultas;
    data['awardee_nama_pa'] = awardeeNamaPa;
    data['awardee_telephone_pa'] = awardeeTelephonePa;
    data['awardee_email_pa'] = awardeeEmailPa;
    data['awardee_nama_promotor'] = awardeeNamaPromotor;
    data['awardee_telephone_promotor'] = awardeeTelephonePromotor;
    data['awardee_email_promotor'] = awardeeEmailPromotor;
    data['awardee_tanggal_masuk'] = awardeeTanggalMasuk;
    data['awardee_batas_studi'] = awardeeBatasStudi;
    data['awardee_tanggal_lulus'] = awardeeTanggalLulus;
    data['awardee_tanggal_yudisium'] = awardeeTanggalYudisium;
    data['awardee_nomor_ijazah'] = awardeeNomorIjazah;
    data['perkembangan_ipk'] = perkembanganIpk;
    data['awardee_jurusan_universitas'] = awardeeJurusanUniversitas;
    data['pns_unit_eselon_1'] = pnsUnitEselon_1;
    data['pns_unit_eselon_2'] = pnsUnitEselon_2;
    data['id_fakultas'] = idFakultas;
    data['id_program_studi'] = idProgramStudi;
    data['hak_spp'] = hakSpp;
    data['ishaveloafromseleksi'] = ishaveloafromseleksi;
    data['is_active'] = isActive;
    data['template_sp'] = templateSp;
    data['template_sk'] = templateSk;
    data['nextstatus'] = nextstatus;
    data['role'] = role;
    data['idmodule'] = idmodule;
    return data;
  }
}
